INSERT INTO "public"."g2p_attribute_values" ("value_id","attribute_id","value_code","value_display","parent_value_id","sort_order") VALUES

-- HEADSHIP TYPE
('HEADSHIP_TYPE_FEMALE_HEADED','HEADSHIP_TYPE','FEMALE_HEADED','Female Headed',NULL,'1'),
('HEADSHIP_TYPE_CHILD_HEADED','HEADSHIP_TYPE','CHILD_HEADED','Child Headed',NULL,'2'),
('HEADSHIP_TYPE_ELDERLY_HEADED','HEADSHIP_TYPE','ELDERLY_HEADED','Elderly Headed',NULL,'3'),
('HEADSHIP_TYPE_DISABLED_HEADED','HEADSHIP_TYPE','DISABLED_HEADED','Disabled Headed',NULL,'4'),
('HEADSHIP_TYPE_MALE_HEADED','HEADSHIP_TYPE','MALE_HEADED','Male Headed',NULL,'5'),

-- RESIDENCY STATUS
('RESIDENCY_STATUS_USUAL_MEMBER','RESIDENCY_STATUS','USUAL_MEMBER','Usual Member',NULL,'1'),
('RESIDENCY_STATUS_TEMPORARY','RESIDENCY_STATUS','TEMPORARY','Temporary',NULL,'2'),
('RESIDENCY_STATUS_ABSENT','RESIDENCY_STATUS','ABSENT','Absent',NULL,'3'),

-- RELATIONSHIP TO HEAD
('RELATIONSHIP_TO_HEAD_SPOUSE','RELATIONSHIP_TO_HEAD','SPOUSE','Spouse',NULL,'1'),
('RELATIONSHIP_TO_HEAD_CHILD','RELATIONSHIP_TO_HEAD','CHILD','Child',NULL,'2'),
('RELATIONSHIP_TO_HEAD_PARENT','RELATIONSHIP_TO_HEAD','PARENT','Parent',NULL,'3'),
('RELATIONSHIP_TO_HEAD_OTHER','RELATIONSHIP_TO_HEAD','OTHER','Other',NULL,'4'),

-- PREFERRED CONTACT METHOD
('PREFERRED_CONTACT_METHOD_CALL','PREFERRED_CONTACT_METHOD','CALL','Call',NULL,'1'),
('PREFERRED_CONTACT_METHOD_SMS','PREFERRED_CONTACT_METHOD','SMS','Sms',NULL,'2'),
('PREFERRED_CONTACT_METHOD_THROUGH_KEBELE','PREFERRED_CONTACT_METHOD','THROUGH_KEBELE','Through Kebele',NULL,'3'),

-- CITIZENSHIP CATEGORY
('CITIZENSHIP_CATEGORY_CITIZEN','CITIZENSHIP_CATEGORY','CITIZEN','Citizen',NULL,'1'),
('CITIZENSHIP_CATEGORY_REFUGEE','CITIZENSHIP_CATEGORY','REFUGEE','Refugee',NULL,'2'),
('CITIZENSHIP_CATEGORY_IDP','CITIZENSHIP_CATEGORY','IDP','IDP',NULL,'3'),
('CITIZENSHIP_CATEGORY_RETURNEE','CITIZENSHIP_CATEGORY','RETURNEE','Returnee',NULL,'4'),
('CITIZENSHIP_CATEGORY_RESIDENT','CITIZENSHIP_CATEGORY','RESIDENT','Resident',NULL,'5'),

-- DISABILITY STATUS
('DISABILITY_STATUS_YES','DISABILITY_STATUS','YES','Yes',NULL,'1'),
('DISABILITY_STATUS_NO','DISABILITY_STATUS','NO','No',NULL,'2'),
('DISABILITY_STATUS_UNKNOWN','DISABILITY_STATUS','UNKNOWN','Unknown',NULL,'3'),

-- DISABILITY SEVERITY
('DISABILITY_SEVERITY_MILD','DISABILITY_SEVERITY','MILD','Mild',NULL,'1'),
('DISABILITY_SEVERITY_MODERATE','DISABILITY_SEVERITY','MODERATE','Moderate',NULL,'2'),
('DISABILITY_SEVERITY_SEVERE','DISABILITY_SEVERITY','SEVERE','Severe',NULL,'3'),

-- DISABILITY DOMAIN
('DISABILITY_DOMAIN_PHYSICAL','DISABILITY_DOMAIN','PHYSICAL','Physical',NULL,'1'),
('DISABILITY_DOMAIN_SENSORY','DISABILITY_DOMAIN','SENSORY','Sensory',NULL,'2'),
('DISABILITY_DOMAIN_INTELLECTUAL','DISABILITY_DOMAIN','INTELLECTUAL','Intellectual',NULL,'3'),
('DISABILITY_DOMAIN_MENTAL_HEALTH','DISABILITY_DOMAIN','MENTAL_HEALTH','Mental Health',NULL,'4'),
('DISABILITY_DOMAIN_OTHER','DISABILITY_DOMAIN','OTHER','Other',NULL,'5'),

-- DISPLACEMENT STATUS
('DISPLACEMENT_STATUS_IDP','DISPLACEMENT_STATUS','IDP','IDP',NULL,'1'),
('DISPLACEMENT_STATUS_RETURNEE','DISPLACEMENT_STATUS','RETURNEE','Returnee',NULL,'2'),
('DISPLACEMENT_STATUS_REFUGEE','DISPLACEMENT_STATUS','REFUGEE','Refugee',NULL,'3'),
('DISPLACEMENT_STATUS_HOST_COMMUNITY','DISPLACEMENT_STATUS','HOST_COMMUNITY','Host Community',NULL,'4'),

-- PASTORALIST CLASSIFICATION
('PASTORALIST_CLASSIFICATION_PASTORALIST','PASTORALIST_CLASSIFICATION','PASTORALIST','Pastoralist',NULL,'1'),
('PASTORALIST_CLASSIFICATION_SEMI_PASTORALIST','PASTORALIST_CLASSIFICATION','SEMI_PASTORALIST','Semi Pastoralist',NULL,'2'),
('PASTORALIST_CLASSIFICATION_SETTLED','PASTORALIST_CLASSIFICATION','SETTLED','Settled',NULL,'3'),

-- DWELLING TYPE
('DWELLING_TYPE_PERMANENT','DWELLING_TYPE','PERMANENT','Permanent',NULL,'1'),
('DWELLING_TYPE_SEMI','DWELLING_TYPE','SEMI','Semi',NULL,'2'),
('DWELLING_TYPE_TEMPORARY','DWELLING_TYPE','TEMPORARY','Temporary',NULL,'3'),

-- TENURE STATUS
('TENURE_STATUS_OWNED','TENURE_STATUS','OWNED','Owned',NULL,'1'),
('TENURE_STATUS_RENTED','TENURE_STATUS','RENTED','Rented',NULL,'2'),

-- EMPLOYMENT STATUS
('EMPLOYMENT_STATUS_EMPLOYED','EMPLOYMENT_STATUS','EMPLOYED','Employed',NULL,'1'),
('EMPLOYMENT_STATUS_SELF_EMPLOYED','EMPLOYMENT_STATUS','SELF_EMPLOYED','Self Employed',NULL,'2'),
('EMPLOYMENT_STATUS_UNEMPLOYED','EMPLOYMENT_STATUS','UNEMPLOYED','Unemployed',NULL,'3'),
('EMPLOYMENT_STATUS_STUDENT','EMPLOYMENT_STATUS','STUDENT','Student',NULL,'4'),
('EMPLOYMENT_STATUS_OTHER','EMPLOYMENT_STATUS','OTHER','Other',NULL,'5'),

-- SHOCK TYPE
('SHOCK_TYPE_DROUGHT','SHOCK_TYPE','DROUGHT','Drought',NULL,'1'),
('SHOCK_TYPE_FLOOD','SHOCK_TYPE','FLOOD','Flood',NULL,'2'),
('SHOCK_TYPE_CONFLICT','SHOCK_TYPE','CONFLICT','Conflict',NULL,'3'),
('SHOCK_TYPE_ILLNESS','SHOCK_TYPE','ILLNESS','Illness',NULL,'4'),
('SHOCK_TYPE_OTHER','SHOCK_TYPE','OTHER','Other',NULL,'5'),

-- HOUSEHOLD ASSETS
('HOUSEHOLD_ASSETS_RADIO','HOUSEHOLD_ASSETS','RADIO','Radio',NULL,'1'),
('HOUSEHOLD_ASSETS_TV','HOUSEHOLD_ASSETS','TV','Tv',NULL,'2'),
('HOUSEHOLD_ASSETS_FRIDGE','HOUSEHOLD_ASSETS','FRIDGE','Fridge',NULL,'3'),
('HOUSEHOLD_ASSETS_BICYCLE','HOUSEHOLD_ASSETS','BICYCLE','Bicycle',NULL,'4'),
('HOUSEHOLD_ASSETS_MOTORCYCLE','HOUSEHOLD_ASSETS','MOTORCYCLE','Motorcycle',NULL,'5'),

-- MOBILE PHONE TYPE
('MOBILE_PHONE_TYPE_BASIC','MOBILE_PHONE_TYPE','BASIC','Basic',NULL,'1'),
('MOBILE_PHONE_TYPE_SMARTPHONE','MOBILE_PHONE_TYPE','SMARTPHONE','Smartphone',NULL,'2'),

-- LIGHTING SOURCE
('LIGHTING_SOURCE_GRID','LIGHTING_SOURCE','GRID','Grid',NULL,'1'),
('LIGHTING_SOURCE_SOLAR','LIGHTING_SOURCE','SOLAR','Solar',NULL,'2'),
('LIGHTING_SOURCE_KEROSENE','LIGHTING_SOURCE','KEROSENE','Kerosene',NULL,'3'),

-- AGE METHOD
('AGE_METHOD_DOCUMENTED','AGE_METHOD','DOCUMENTED','Documented',NULL,'1'),
('AGE_METHOD_ESTIMATED','AGE_METHOD','ESTIMATED','Estimated',NULL,'2'),
('AGE_METHOD_CALCULATED','AGE_METHOD','CALCULATED','Calculated',NULL,'3'),

-- MARITAL STATUS
('MARITAL_STATUS_SINGLE','MARITAL_STATUS','SINGLE','Single',NULL,'1'),
('MARITAL_STATUS_MARRIED','MARITAL_STATUS','MARRIED','Married',NULL,'2'),
('MARITAL_STATUS_DIVORCED','MARITAL_STATUS','DIVORCED','Divorced',NULL,'3'),
('MARITAL_STATUS_WIDOWED','MARITAL_STATUS','WIDOWED','Widowed',NULL,'4'),
('MARITAL_STATUS_SEPARATED','MARITAL_STATUS','SEPARATED','Separated',NULL,'5'),
('MARITAL_STATUS_UNKNOWN','MARITAL_STATUS','UNKNOWN','Unknown',NULL,'6'),

-- LIVESTOCK SPECIES
('LIVESTOCK_SPECIES_CATTLE','LIVESTOCK_SPECIES','CATTLE','Cattle',NULL,'1'),
('LIVESTOCK_SPECIES_GOATS','LIVESTOCK_SPECIES','GOATS','Goats',NULL,'2'),
('LIVESTOCK_SPECIES_SHEEP','LIVESTOCK_SPECIES','SHEEP','Sheep',NULL,'3'),
('LIVESTOCK_SPECIES_POULTRY','LIVESTOCK_SPECIES','POULTRY','Poultry',NULL,'4'),
('LIVESTOCK_SPECIES_CAMELS','LIVESTOCK_SPECIES','CAMELS','Camels',NULL,'5'),
('LIVESTOCK_SPECIES_EQUINES','LIVESTOCK_SPECIES','EQUINES','Equines',NULL,'6'),
('LIVESTOCK_SPECIES_OTHER','LIVESTOCK_SPECIES','OTHER','Other',NULL,'7'),

-- LIVESTOCK COUNT BAND
('LIVESTOCK_COUNT_BAND_BAND_1_5','LIVESTOCK_COUNT_BAND','BAND_1_5','Band 1-5',NULL,'2'),
('LIVESTOCK_COUNT_BAND_BAND_6_10','LIVESTOCK_COUNT_BAND','BAND_6_10','Band 6-10',NULL,'3'),
('LIVESTOCK_COUNT_BAND_BAND_11_20','LIVESTOCK_COUNT_BAND','BAND_11_20','Band 11-20',NULL,'4'),
('LIVESTOCK_COUNT_BAND_BAND_21_50','LIVESTOCK_COUNT_BAND','BAND_21_50','Band 21-50',NULL,'5'),
('LIVESTOCK_COUNT_BAND_BAND_50_PLUS','LIVESTOCK_COUNT_BAND','BAND_50_PLUS','Band 50 Plus',NULL,'6'),

-- DATA QUALITY FLAGS
('DATA_QUALITY_FLAGS_MISSING_KEY_FIELDS','DATA_QUALITY_FLAGS','MISSING_KEY_FIELDS','Missing Key Fields',NULL,'1'),
('DATA_QUALITY_FLAGS_SUSPECTED_DUPLICATE','DATA_QUALITY_FLAGS','SUSPECTED_DUPLICATE','Suspected Duplicate',NULL,'2'),
('DATA_QUALITY_FLAGS_INCONSISTENT','DATA_QUALITY_FLAGS','INCONSISTENT','Inconsistent',NULL,'3'),

-- LIVELIHOOD
('LIVELIHOOD_AGRICULTURE','LIVELIHOOD','AGRICULTURE','Agriculture',NULL,'1'),
('LIVELIHOOD_LIVESTOCK','LIVELIHOOD','LIVESTOCK','Livestock',NULL,'2'),
('LIVELIHOOD_FISHING','LIVELIHOOD','FISHING','Fishing',NULL,'3'),
('LIVELIHOOD_WAGE_LABOR','LIVELIHOOD','WAGE_LABOR','Wage Labor',NULL,'4'),
('LIVELIHOOD_SELF_EMPLOYMENT','LIVELIHOOD','SELF_EMPLOYMENT','Self Employment',NULL,'5'),
('LIVELIHOOD_GOVERNMENT_EMPLOYEE','LIVELIHOOD','GOVERNMENT_EMPLOYEE','Government Employee',NULL,'6'),
('LIVELIHOOD_PRIVATE_SECTOR_EMPLOYEE','LIVELIHOOD','PRIVATE_SECTOR_EMPLOYEE','Private Sector Employee',NULL,'7'),
('LIVELIHOOD_BUSINESS_TRADE','LIVELIHOOD','BUSINESS_TRADE','Business Trade',NULL,'8'),
('LIVELIHOOD_REMITTANCE','LIVELIHOOD','REMITTANCE','Remittance',NULL,'9'),
('LIVELIHOOD_PENSION','LIVELIHOOD','PENSION','Pension',NULL,'10'),
('LIVELIHOOD_UNEMPLOYED','LIVELIHOOD','UNEMPLOYED','Unemployed',NULL,'11'),
('LIVELIHOOD_OTHER','LIVELIHOOD','OTHER','Other',NULL,'12'),

-- ROOF MATERIAL
('ROOF_MATERIAL_THATCH','ROOF_MATERIAL','THATCH','Thatch',NULL,'1'),
('ROOF_MATERIAL_CORRUGATED_IRON','ROOF_MATERIAL','CORRUGATED_IRON','Corrugated Iron',NULL,'2'),
('ROOF_MATERIAL_CONCRETE','ROOF_MATERIAL','CONCRETE','Concrete',NULL,'3'),
('ROOF_MATERIAL_TILE','ROOF_MATERIAL','TILE','Tile',NULL,'4'),
('ROOF_MATERIAL_PLASTIC_SHEET','ROOF_MATERIAL','PLASTIC_SHEET','Plastic Sheet',NULL,'5'),
('ROOF_MATERIAL_OTHER','ROOF_MATERIAL','OTHER','Other',NULL,'6'),

-- WALL MATERIAL
('WALL_MATERIAL_MUD','WALL_MATERIAL','MUD','Mud',NULL,'1'),
('WALL_MATERIAL_WOOD','WALL_MATERIAL','WOOD','Wood',NULL,'2'),
('WALL_MATERIAL_BAMBOO','WALL_MATERIAL','BAMBOO','Bamboo',NULL,'3'),
('WALL_MATERIAL_STONE','WALL_MATERIAL','STONE','Stone',NULL,'4'),
('WALL_MATERIAL_BRICK','WALL_MATERIAL','BRICK','Brick',NULL,'5'),
('WALL_MATERIAL_CONCRETE','WALL_MATERIAL','CONCRETE','Concrete',NULL,'6'),
('WALL_MATERIAL_OTHER','WALL_MATERIAL','OTHER','Other',NULL,'7'),

-- FLOOR MATERIAL
('FLOOR_MATERIAL_EARTH','FLOOR_MATERIAL','EARTH','Earth',NULL,'1'),
('FLOOR_MATERIAL_WOOD','FLOOR_MATERIAL','WOOD','Wood',NULL,'2'),
('FLOOR_MATERIAL_CEMENT','FLOOR_MATERIAL','CEMENT','Cement',NULL,'3'),
('FLOOR_MATERIAL_TILE','FLOOR_MATERIAL','TILE','Tile',NULL,'4'),
('FLOOR_MATERIAL_OTHER','FLOOR_MATERIAL','OTHER','Other',NULL,'5'),

-- COOKING FUEL TYPE
('COOKING_FUEL_TYPE_FIREWOOD','COOKING_FUEL_TYPE','FIREWOOD','Firewood',NULL,'1'),
('COOKING_FUEL_TYPE_CHARCOAL','COOKING_FUEL_TYPE','CHARCOAL','Charcoal',NULL,'2'),
('COOKING_FUEL_TYPE_ELECTRICITY','COOKING_FUEL_TYPE','ELECTRICITY','Electricity',NULL,'3'),
('COOKING_FUEL_TYPE_LPG','COOKING_FUEL_TYPE','LPG','Lpg',NULL,'4'),
('COOKING_FUEL_TYPE_BIOGAS','COOKING_FUEL_TYPE','BIOGAS','Biogas',NULL,'5'),
('COOKING_FUEL_TYPE_KEROSENE','COOKING_FUEL_TYPE','KEROSENE','Kerosene',NULL,'6'),
('COOKING_FUEL_TYPE_DUNG','COOKING_FUEL_TYPE','DUNG','Dung',NULL,'7'),
('COOKING_FUEL_TYPE_OTHER','COOKING_FUEL_TYPE','OTHER','Other',NULL,'8'),

-- WATER SOURCE TYPE
('WATER_SOURCE_TYPE_PIPED','WATER_SOURCE_TYPE','PIPED','Piped',NULL,'1'),
('WATER_SOURCE_TYPE_BOREHOLE','WATER_SOURCE_TYPE','BOREHOLE','Borehole',NULL,'2'),
('WATER_SOURCE_TYPE_PROTECTED_WELL','WATER_SOURCE_TYPE','PROTECTED_WELL','Protected Well',NULL,'3'),
('WATER_SOURCE_TYPE_UNPROTECTED_WELL','WATER_SOURCE_TYPE','UNPROTECTED_WELL','Unprotected Well',NULL,'4'),
('WATER_SOURCE_TYPE_SPRING','WATER_SOURCE_TYPE','SPRING','Spring',NULL,'5'),
('WATER_SOURCE_TYPE_RIVER','WATER_SOURCE_TYPE','RIVER','River',NULL,'6'),
('WATER_SOURCE_TYPE_RAINWATER','WATER_SOURCE_TYPE','RAINWATER','Rainwater',NULL,'7'),
('WATER_SOURCE_TYPE_TANKER_TRUCK','WATER_SOURCE_TYPE','TANKER_TRUCK','Tanker Truck',NULL,'8'),
('WATER_SOURCE_TYPE_OTHER','WATER_SOURCE_TYPE','OTHER','Other',NULL,'9'),

-- SANITATION TYPE
('SANITATION_TYPE_FLUSH_TOILET','SANITATION_TYPE','FLUSH_TOILET','Flush Toilet',NULL,'1'),
('SANITATION_TYPE_PIT_LATRINE','SANITATION_TYPE','PIT_LATRINE','Pit Latrine',NULL,'2'),
('SANITATION_TYPE_VENTILATED_IMPROVED_PIT','SANITATION_TYPE','VENTILATED_IMPROVED_PIT','Ventilated Improved Pit',NULL,'3'),
('SANITATION_TYPE_COMPOSTING_TOILET','SANITATION_TYPE','COMPOSTING_TOILET','Composting Toilet',NULL,'4'),
('SANITATION_TYPE_OPEN_DEFECATION','SANITATION_TYPE','OPEN_DEFECATION','Open Defecation',NULL,'5'),
('SANITATION_TYPE_OTHER','SANITATION_TYPE','OTHER','Other',NULL,'6'),

-- PRODUCTIVE ASSET
('PRODUCTIVE_ASSET_PLOUGH','PRODUCTIVE_ASSET','PLOUGH','Plough',NULL,'1'),
('PRODUCTIVE_ASSET_IRRIGATION_PUMP','PRODUCTIVE_ASSET','IRRIGATION_PUMP','Irrigation Pump',NULL,'2'),
('PRODUCTIVE_ASSET_OTHER','PRODUCTIVE_ASSET','OTHER','Other',NULL,'3'),

-- PROGRAMS
('PROGRAM_UPSNP','PROGRAM','UPSNP','UPSNP',NULL,'1'),
('PROGRAM_RPSNP','PROGRAM','RPSNP','RPSNP',NULL,'2'),

-- EDUCATIONAL STATUS
('EDUCATIONAL_STATUS_NEVER_ATTEND','EDUCATIONAL_STATUS','NEVER_ATTEND','Never Attend',NULL,'1'),
('EDUCATIONAL_STATUS_NON_FORMAL','EDUCATIONAL_STATUS','NON_FORMAL','Non Formal',NULL,'2'),
('EDUCATIONAL_STATUS_PRIMARY','EDUCATIONAL_STATUS','PRIMARY','Primary',NULL,'3'),
('EDUCATIONAL_STATUS_SECONDARY','EDUCATIONAL_STATUS','SECONDARY','Secondary',NULL,'4'),
('EDUCATIONAL_STATUS_HIGHER_EDUCATION','EDUCATIONAL_STATUS','HIGHER_EDUCATION','Higher Education',NULL,'5'),

-- PREFIX
('PREFIX_MR','PREFIX','Mr','Mr',NULL,'1'),
('PREFIX_MRS','PREFIX','Mrs','Mrs',NULL,'2'),
('PREFIX_MISS','PREFIX','Miss','Miss',NULL,'3'),

-- GENDER
('GENDER_MALE','GENDER','MALE','Male',NULL,'1'),
('GENDER_FEMALE','GENDER','FEMALE','Female',NULL,'2'),
('GENDER_OTHERS','GENDER','OTHERS','Others',NULL,'3')
ON CONFLICT (value_id) DO UPDATE
SET attribute_id    = EXCLUDED.attribute_id,
    value_code      = EXCLUDED.value_code,
    value_display   = EXCLUDED.value_display,
    parent_value_id = EXCLUDED.parent_value_id,
    sort_order      = EXCLUDED.sort_order;