INSERT INTO "public"."g2p_attributes" ("attribute_id","attribute_code","attribute_display","is_hierarchical") VALUES
('HEADSHIP_TYPE','HEADSHIP_TYPE','Headship Type','FALSE'),
('RESIDENCY_STATUS','RESIDENCY_STATUS','Residency Status','FALSE'),
('RELATIONSHIP_TO_HEAD','RELATIONSHIP_TO_HEAD','Relationship To Head','FALSE'),
('PREFERRED_CONTACT_METHOD','PREFERRED_CONTACT_METHOD','Preferred Contact Method','FALSE'),
('CITIZENSHIP_CATEGORY','CITIZENSHIP_CATEGORY','Citizenship Category','FALSE'),
('DISABILITY_STATUS','DISABILITY_STATUS','Disability Status','FALSE'),
('DISABILITY_SEVERITY','DISABILITY_SEVERITY','Disability Severity','FALSE'),
('DISABILITY_DOMAIN','DISABILITY_DOMAIN','Disability Domain','FALSE'),
('DISPLACEMENT_STATUS','DISPLACEMENT_STATUS','Displacement Status','FALSE'),
('PASTORALIST_CLASSIFICATION','PASTORALIST_CLASSIFICATION','Pastoralist Classification','FALSE'),
('DWELLING_TYPE','DWELLING_TYPE','Dwelling Type','FALSE'),
('TENURE_STATUS','TENURE_STATUS','Tenure Status','FALSE'),
('EMPLOYMENT_STATUS','EMPLOYMENT_STATUS','Employment Status','FALSE'),
('SHOCK_TYPE','SHOCK_TYPE','Shock Type','FALSE'),
('HOUSEHOLD_ASSETS','HOUSEHOLD_ASSETS','Household Assets','FALSE'),
('MOBILE_PHONE_TYPE','MOBILE_PHONE_TYPE','Mobile Phone Type','FALSE'),
('LIGHTING_SOURCE','LIGHTING_SOURCE','Lighting Source','FALSE'),
('AGE_METHOD','AGE_METHOD','Age Method','FALSE'),
('MARITAL_STATUS','MARITAL_STATUS','Marital Status','FALSE'),
('LIVESTOCK_SPECIES','LIVESTOCK_SPECIES','Livestock Species','FALSE'),
('LIVESTOCK_COUNT_BAND','LIVESTOCK_COUNT_BAND','Livestock Count Band','FALSE'),
('DATA_QUALITY_FLAGS','DATA_QUALITY_FLAGS','Data Quality Flags','FALSE'),
('LIVELIHOOD','LIVELIHOOD','Livelihood','FALSE'),
('ROOF_MATERIAL','ROOF_MATERIAL','Roof Material','FALSE'),
('WALL_MATERIAL','WALL_MATERIAL','Wall Material','FALSE'),
('FLOOR_MATERIAL','FLOOR_MATERIAL','Floor Material','FALSE'),
('COOKING_FUEL_TYPE','COOKING_FUEL_TYPE','Cooking Fuel Type','FALSE'),
('WATER_SOURCE_TYPE','WATER_SOURCE_TYPE','Water Source Type','FALSE'),
('SANITATION_TYPE','SANITATION_TYPE','Sanitation Type','FALSE'),
('PRODUCTIVE_ASSET','PRODUCTIVE_ASSET','Productive Asset','FALSE'),
('PROGRAM','PROGRAM','Program','FALSE'),
('EDUCATIONAL_STATUS','EDUCATIONAL_STATUS','Educational Status','FALSE'),
('PREFIX','PREFIX','Prefix','FALSE'),
('GENDER','GENDER','Gender','FALSE')
ON CONFLICT (attribute_id) DO UPDATE
SET attribute_code    = EXCLUDED.attribute_code,
    attribute_display = EXCLUDED.attribute_display,
    is_hierarchical   = EXCLUDED.is_hierarchical;
