INSERT INTO
  "public"."g2p_register_sections" (
    "register_id",
    "section_id",
    "section_register_id",
    "is_core_section",
    "section_mnemonic",
    "section_description",
    "documents_required",
    "no_of_verifications_required",
    "is_list",
    "section_weightage",
    "section_ui_schema",
    "cr_auto_approve_for_bene_portal",
    "cr_auto_approve_for_agent_portal",
    "cr_auto_approve_for_staff_portal",
    "cr_auto_approve_for_partner"
  )
VALUES
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'c6690d90-044b-4469-82f3-057bb2f739c9',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_authentication',
    'Individual Authentication',
    'FALSE',
    0,
    'FALSE',
    15,
    '{"panels": [{"panels": [{"widgets": [{"widget": "id-authentication", "widget-id": "id-auth", "widget-type": "group", "widget-readonly": true, "widget-data-path": {"expiryDate": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.authentication_expiry_at", "foundationalId": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.foundational_id", "internalRecordId": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.internal_record_id", "initiatedByStaffId": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.last_approved_by", "authenticationToken": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.authentication_token", "lastAuthenticatedOn": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.last_authenticated_at", "lastAuthenticationStatus": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.last_authentication_status"}, "widget-auth-config": {"service": "register", "providerId": "199c9a49-4b4e-4fda-b893-92c6558312d8", "registerId": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd", "providerName": "esignet", "authenticateMethod": "POST", "authenticateEndpoint": "authenticate_registrant"}}], "panel-id": "vertical_panel_authentication", "panel-column-span": 3, "panel-orientation": "vertical"}], "panel-id": "horizontal_panel_authentication", "panel-orientation": "horizontal"}], "section-id": "register_authentication", "section-title": "Authentication", "section-editable": false}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_header_info_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_header_info',
    'Household Header Info',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "header-section", "widget-id": "registry-header", "widget-type": "group", "widget-data-path": {"name": "9055ab43-c85d-4833-bd00-ca657bb72644.record_name", "image": "9055ab43-c85d-4833-bd00-ca657bb72644.record_image_storage_id", "status": "9055ab43-c85d-4833-bd00-ca657bb72644.record_status", "createdAt": "9055ab43-c85d-4833-bd00-ca657bb72644.created_at", "createdBy": "9055ab43-c85d-4833-bd00-ca657bb72644.created_by", "idealScore": "9055ab43-c85d-4833-bd00-ca657bb72644.ideal_score", "functionalId": "9055ab43-c85d-4833-bd00-ca657bb72644.functional_record_id", "statusReason": "9055ab43-c85d-4833-bd00-ca657bb72644.record_status_reason", "lastApprovedAt": "9055ab43-c85d-4833-bd00-ca657bb72644.last_approved_at", "lastApprovedBy": "9055ab43-c85d-4833-bd00-ca657bb72644.last_approved_by", "completionScore": "9055ab43-c85d-4833-bd00-ca657bb72644.actual_score"}, "widget-data-format": {"imageSize": 120, "nameColor": "#ED7C22", "statusColors": {"ACTIVE": "#16A34A", "ARCHIVED": "#6B7280", "INACTIVE": "#D97706"}}, "widget-field-config": {"status": {"data-source": {"type": "static", "options": [{"label": "ACTIVE", "value": "ACTIVE"}, {"label": "INACTIVE", "value": "INACTIVE"}, {"label": "ARCHIVED", "value": "ARCHIVED"}]}}}}], "panel-id": "household_header_inside_panel", "panel-orientation": "vertical"}], "panel-id": "household_header_outside_panel", "panel-orientation": "horizontal"}], "section-id": "household_header", "section-title": "", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_programs_section',
    'b7a943c3-ce2f-45e2-84a3-1e8a8aad0545',
    'FALSE',
    'household_program',
    'Household Programs',
    'FALSE',
    0,
    'TRUE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "table", "widget-id": "household_programs_table", "widget-type": "table", "widget-label": "Program Enrollments", "widget-readonly": false, "widget-data-path": "b7a943c3-ce2f-45e2-84a3-1e8a8aad0545.records", "widget-data-columns": [{"widget": "text", "column-key": "program_id", "widget-type": "input", "widget-label": "Program ID", "widget-data-path": "program_id"}, {"widget": "select", "column-key": "program_name", "widget-type": "input", "widget-label": "Program Name", "widget-data-path": "program_name", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "PROGRAM"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "date", "column-key": "program_start_date", "widget-type": "input", "widget-label": "Start Date", "widget-data-path": "program_start_date", "widget-data-options": {"maxDate": "today"}}, {"widget": "date", "column-key": "program_exit_date", "widget-type": "input", "widget-label": "Exit Date", "widget-data-path": "program_exit_date", "widget-data-options": {"minDateField": "program_start_date", "minDateMessage": "Exit date must be on or after the start date"}}], "widget-data-add-label": "Add Program", "widget-data-operations": {"add": true, "edit": true, "remove": true}}], "panel-id": "vertical_panel_household_programs", "panel-column-span": 3, "panel-orientation": "vertical"}], "panel-id": "horizontal_panel_household_programs", "panel-orientation": "horizontal"}], "section-id": "household_programs", "section-title": "household_programs", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_location_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_location_details',
    'Household Location Details',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "geo-hierarchy", "widget-id": "household_geo_hierarchy", "widget-type": "input", "widget-label": "Location Hierarchy", "widget-required": true, "widget-data-path": {"value": "9055ab43-c85d-4833-bd00-ca657bb72644.geo_lowest_level_value_id", "hierarchy": "9055ab43-c85d-4833-bd00-ca657bb72644.geo_code_hierarchy_json"}, "widget-geo-layout": {"columnSpan": 1}, "widget-data-source": {"type": "api", "method": "POST", "service": "master-data", "levelsEndpoint": "get-all-g2p-geo-levels", "valuesEndpoint": "geo-level-values"}}], "panel-id": "panel_geo_main", "panel-column-span": 1, "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "kebele_code", "widget-type": "input", "widget-label": "Kebele", "widget-readonly": false, "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.kebele_code", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F0-9 .\\/''-]+$", "maxLength": 50, "patternMessage": "Only letters, numbers, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}, {"widget": "text", "widget-id": "locality_ea_code", "widget-type": "input", "widget-label": "Locality / EA Code", "widget-readonly": false, "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.locality_ea_code", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F0-9 .\\/''-]+$", "maxLength": 50, "patternMessage": "Only letters, numbers, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}, {"widget": "textarea", "widget-id": "address_descriptor", "widget-type": "input", "widget-label": "Address Descriptor", "widget-readonly": false, "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.address_descriptor", "widget-data-format": {"rows": 2, "caseControl": "none", "characterType": "any", "showCharCounter": true}, "widget-data-validation": {"maxLength": 500, "minLength": 6}, "widget-data-placeholder": "Enter address descriptor"}], "panel-id": "panel_location_2", "panel-column-span": 1, "panel-orientation": "vertical"}, {"widgets": [{"widget": "number", "widget-id": "gps_latitude", "widget-type": "input", "widget-label": "GPS Latitude", "widget-readonly": false, "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.gps_latitude", "widget-data-format": {"textAlign": "right", "allowSigned": true, "numericType": "decimal", "formatOnBlur": true, "roundingMode": "round", "decimalPlaces": 6, "decimalSeparator": ".", "thousandSeparator": ","}, "widget-data-validation": {"max": 90, "min": -90, "pattern": "^[0-9]+(\\.[0-9]{1,2})?$", "patternMessage": "Invalid number format"}, "widget-data-placeholder": "Enter latitude"}, {"widget": "number", "widget-id": "gps_longitude", "widget-type": "input", "widget-label": "GPS Longitude", "widget-readonly": false, "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.gps_longitude", "widget-data-format": {"textAlign": "right", "allowSigned": true, "numericType": "decimal", "formatOnBlur": true, "roundingMode": "round", "decimalPlaces": 6, "decimalSeparator": ".", "thousandSeparator": ","}, "widget-data-validation": {"max": 180, "min": -180, "pattern": "^[0-9]+(\\.[0-9]{1,2})?$", "patternMessage": "Invalid number format"}, "widget-data-placeholder": "Enter longitude"}, {"widget": "number", "widget-id": "gps_accuracy", "widget-type": "input", "widget-label": "GPS Accuracy", "widget-readonly": false, "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.gps_accuracy", "widget-data-format": {"textAlign": "right", "allowSigned": true, "numericType": "decimal", "formatOnBlur": true, "roundingMode": "round", "decimalPlaces": 6, "decimalSeparator": ".", "thousandSeparator": ","}, "widget-data-validation": {"max": 10000, "min": 0, "pattern": "^[0-9]+(\\.[0-9]{1,2})?$", "patternMessage": "Invalid number format"}, "widget-data-placeholder": "Enter GPS accuracy"}], "panel-id": "panel_location_3", "panel-column-span": 1, "panel-orientation": "vertical"}], "panel-id": "panel_location_details_main", "panel-orientation": "horizontal"}], "section-id": "household_location_details", "section-title": "location_details", "section-editable": true, "section-column-span": 3, "section-supporting-documents": []}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_roster_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_roster',
    'Household Roster',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "display", "widget-id": "household_size_total", "widget-type": "input", "widget-label": "Household Size Total", "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.household_size_total", "widget-data-validation": {"min": 0, "pattern": "^[0-9]{0,2}$", "maxLength": 2, "minLength": 0}}, {"widget": "display", "widget-id": "household_size_adults", "widget-type": "input", "widget-label": "Household Size Adults", "widget-readonly": true, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.household_size_adults", "widget-data-validation": {"min": 0, "pattern": "^[0-9]{0,2}$", "maxLength": 2, "minLength": 0}}, {"widget": "display", "widget-id": "household_size_children_u5", "widget-type": "input", "widget-label": "Household Size Children U5", "widget-readonly": true, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.household_size_children_u5", "widget-data-validation": {"min": 0, "pattern": "^[0-9]{0,2}$", "maxLength": 2, "minLength": 0}}], "panel-id": "panel_column_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "display", "widget-id": "household_size_school_age", "widget-type": "input", "widget-label": "Household Size School Age", "widget-readonly": true, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.household_size_school_age", "widget-data-validation": {"min": 0, "pattern": "^[0-9]{0,2}$", "maxLength": 2, "minLength": 0}}, {"widget": "display", "widget-id": "elderly_member_present", "widget-type": "input", "widget-label": "Elderly Member Present", "widget-readonly": true, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.elderly_member_present"}, {"widget": "display", "widget-id": "household_size_elderly", "widget-type": "input", "widget-label": "Household Size Elderly", "widget-readonly": true, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.household_size_elderly", "widget-data-options": {"action": "show", "condition": {"field": "9055ab43-c85d-4833-bd00-ca657bb72644.elderly_member_present", "value": true, "operator": "equals"}}, "widget-data-validation": {"min": 0, "pattern": "^[0-9]{0,2}$", "maxLength": 2, "minLength": 0}}, {"widget": "select", "widget-id": "headship_type", "widget-type": "input", "widget-label": "Headship Type", "widget-readonly": false, "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.headship_type", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "HEADSHIP_TYPE"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_column_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "multi-select", "widget-id": "household_assets", "widget-type": "input", "widget-label": "Household Assets", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.household_assets", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "HOUSEHOLD_ASSETS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_column_3", "panel-orientation": "vertical"}], "panel-id": "panel_household_roster_main", "panel-orientation": "horizontal"}], "section-id": "household_roster", "section-title": "household_roster", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_scores_section',
    'c51e60ca-9990-4077-8d62-0b414ea7e66d',
    'FALSE',
    'household_computation_scores',
    'Computation Scores',
    'FALSE',
    0,
    'TRUE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "scores-display", "widget-id": "record-scores", "widget-type": "group", "widget-readonly": true, "widget-data-path": "c51e60ca-9990-4077-8d62-0b414ea7e66d.records"}], "panel-id": "vertical_panel_scores", "panel-column-span": 3, "panel-orientation": "vertical"}], "panel-id": "horizontal_panel_scores", "panel-orientation": "horizontal"}], "section-id": "register_scores", "section-title": "computation_scores", "section-editable": false}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_shocks_section',
    '6db2adda-3b6c-4499-a613-a187aeaee960',
    'FALSE',
    'household_shocks',
    'Household Shocks',
    'FALSE',
    0,
    'TRUE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "table", "widget-id": "household_shocks_table", "widget-type": "table", "widget-label": "Shocks", "widget-readonly": false, "widget-data-path": "6db2adda-3b6c-4499-a613-a187aeaee960.records", "widget-data-columns": [{"widget": "select", "column-key": "shocks_last_12m", "widget-type": "input", "widget-label": "Shock Type", "widget-data-path": "shocks_last_12m", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "SHOCK_TYPE"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "date", "column-key": "shock_start_date", "widget-type": "input", "widget-label": "Start Date", "widget-data-path": "shock_start_date", "widget-data-options": {"maxDate": "today"}}, {"widget": "date", "column-key": "shock_end_date", "widget-type": "input", "widget-label": "End Date", "widget-data-path": "shock_end_date", "widget-data-options": {"minDateField": "shock_start_date", "minDateMessage": "End date must be on or after the start date"}}], "widget-data-add-label": "Add Shock", "widget-data-operations": {"add": true, "edit": true, "remove": true}}], "panel-id": "vertical_panel_household_shocks", "panel-column-span": 3, "panel-orientation": "vertical"}], "panel-id": "horizontal_panel_household_shocks", "panel-orientation": "horizontal"}], "section-id": "household_shocks", "section-title": "household_shocks", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'housing_and_services_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'housing_and_services',
    'Housing and Services',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "select", "widget-id": "dwelling_type", "widget-type": "input", "widget-label": "Dwelling Type", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.dwelling_type", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "DWELLING_TYPE"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "roof_material", "widget-type": "input", "widget-label": "Roof Material", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.roof_material", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "ROOF_MATERIAL"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "wall_material", "widget-type": "input", "widget-label": "Wall Material", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.wall_material", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "WALL_MATERIAL"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "floor_material", "widget-type": "input", "widget-label": "Floor Material", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.floor_material", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "FLOOR_MATERIAL"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_column_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "select", "widget-id": "tenure_status", "widget-type": "input", "widget-label": "Tenure Status", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.tenure_status", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "TENURE_STATUS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "water_source_type", "widget-type": "input", "widget-label": "Water Source Type", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.water_source_type", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "WATER_SOURCE_TYPE"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "number", "widget-id": "water_distance_minutes", "widget-type": "input", "widget-label": "Water Distance (Minutes)", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.water_distance_minutes", "widget-data-validation": {"min": 0}}, {"widget": "select", "widget-id": "sanitation_type", "widget-type": "input", "widget-label": "Sanitation Type", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.sanitation_type", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "SANITATION_TYPE"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_column_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "select", "widget-id": "lighting_source", "widget-type": "input", "widget-label": "Lighting Source", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.lighting_source", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "LIGHTING_SOURCE"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "cooking_fuel_type", "widget-type": "input", "widget-label": "Cooking Fuel Type", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.cooking_fuel_type", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "COOKING_FUEL_TYPE"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "number", "widget-id": "rooms_count", "widget-type": "input", "widget-label": "Number of Rooms", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.rooms_count", "widget-data-validation": {"min": 0, "pattern": "^[0-9]{0,2}$", "maxLength": 2, "minLength": 0, "patternMessage": "Invalid Number"}}, {"widget": "display", "widget-id": "overcrowding_indicator", "widget-type": "input", "widget-label": "Overcrowding Indicator", "widget-readonly": true, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.overcrowding_indicator", "widget-data-validation": {"min": 0, "pattern": "^[0-9]{0,2}$", "maxLength": 2, "minLength": 0, "patternMessage": "Invalid Number"}}], "panel-id": "panel_column_3", "panel-orientation": "vertical"}], "panel-id": "panel_housing_details_main", "panel-orientation": "horizontal"}], "section-id": "household_housing_and_services_tab", "section-title": "housing_and_services", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_contact_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_contact_details',
    'Contact Details',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "text", "widget-id": "primary_phone", "widget-type": "input", "widget-label": "Primary Phone", "widget-required": true, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.primary_phone", "widget-data-validation": {"pattern": "^(?:\\+251|0)?(?:9|7)\\d{8}$", "maxLength": 13, "minLength": 10, "patternMessage": "Enter a valid phone number starting with +2519/+2517 or 09/07 followed by 8 digits"}}, {"widget": "text", "widget-id": "contact_person_name", "widget-type": "input", "widget-label": "Contact Person Name", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.contact_person_name", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F .\\/''-]+$", "maxLength": 50, "minLength": 2, "patternMessage": "Only letters, spaces, apostrophes, hyphens, and dots are allowed"}}], "panel-id": "panel_contact_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "alternate_phone", "widget-type": "input", "widget-label": "Alternate Phone", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.alternate_phone", "widget-data-validation": {"pattern": "^(?:\\+251|0)?(?:9|7)\\d{8}$", "maxLength": 13, "minLength": 10, "patternMessage": "Enter a valid phone number starting with +2519/+2517 or 09/07 followed by 8 digits"}}, {"widget": "text", "widget-id": "contact_person_phone", "widget-type": "input", "widget-label": "Contact Person Phone", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.contact_person_phone", "widget-data-validation": {"pattern": "^(?:\\+251|0)?(?:9|7)\\d{8}$", "maxLength": 13, "minLength": 10, "patternMessage": "Enter a valid phone number starting with +2519/+2517 or 09/07 followed by 8 digits"}}], "panel-id": "panel_contact_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "select", "widget-id": "preferred_contact_method", "widget-type": "input", "widget-label": "Preferred Contact Method", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.preferred_contact_method", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "PREFERRED_CONTACT_METHOD"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_contact_3", "panel-orientation": "vertical"}], "panel-id": "panel_contact_details_main", "panel-orientation": "horizontal"}], "section-id": "individual_contact_details", "section-title": "contact_details", "section-editable": true, "section-supporting-documents": []}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_livelihood_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_livelihood',
    'Individual Livelihood',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "select", "widget-id": "primary_livelihood", "widget-type": "input", "widget-label": "Primary Livelihood", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.primary_livelihood", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "LIVELIHOOD"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "mobile_phone_type", "widget-type": "input", "widget-label": "Mobile Phone Type", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.mobile_phone_type", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "MOBILE_PHONE_TYPE"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_livelihood_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "select", "widget-id": "secondary_livelihood", "widget-type": "input", "widget-label": "Secondary Livelihood", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.secondary_livelihood", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "LIVELIHOOD"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "educational_status", "widget-type": "input", "widget-label": "Educational Status", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.educational_status", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "EDUCATIONAL_STATUS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_livelihood_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "select", "widget-id": "employment_status", "widget-type": "input", "widget-label": "Employment Status", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.employment_status", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "EMPLOYMENT_STATUS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_livelihood_3", "panel-orientation": "vertical"}], "panel-id": "panel_livelihood_main", "panel-orientation": "horizontal"}], "section-id": "individual_livelihood", "section-title": "individual_livelihood", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_demographic_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_demographic_details',
    'Demographic Details',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "select", "widget-id": "prefix", "widget-type": "input", "widget-label": "Prefix", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.prefix", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "PREFIX"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "text", "widget-id": "first_name", "widget-type": "input", "widget-label": "First Name", "widget-required": true, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.first_name", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F .\\/''-]+$", "maxLength": 50, "minLength": 2, "patternMessage": "Only letters, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}, {"widget": "text", "widget-id": "middle_name", "widget-type": "input", "widget-label": "Middle Name", "widget-required": true, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.middle_name", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F .\\/''-]+$", "maxLength": 50, "minLength": 2, "patternMessage": "Only letters, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}, {"widget": "text", "widget-id": "last_name", "widget-type": "input", "widget-label": "Last Name", "widget-required": true, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.last_name", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F .\\/''-]+$", "maxLength": 50, "minLength": 2, "patternMessage": "Only letters, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}, {"widget": "text", "widget-id": "alias_names", "widget-type": "input", "widget-label": "Alias Names", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.alias_names", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F .\\/''-]+$", "maxLength": 50, "minLength": 2, "patternMessage": "Only letters, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}], "panel-id": "panel_demo_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "date", "widget-id": "birth_date", "widget-type": "input", "widget-label": "Birth Date", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.birth_date", "widget-data-format": {"dateFormat": "DD/MM/YYYY", "dateConstraint": "past-only"}, "widget-data-options": {"action": "disable", "maxDate": "today", "minDate": "1900-01-01", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.estimated_age", "operator": "notEmpty"}}}, {"widget": "number", "widget-id": "estimated_age", "widget-type": "input", "widget-label": "Estimated Age", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.estimated_age", "widget-data-options": {"action": "disable", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.birth_date", "operator": "notEmpty"}}, "widget-data-validation": {"max": 122, "min": 0}}, {"widget": "select", "widget-id": "age_method", "widget-type": "input", "widget-label": "Age Method", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.age_method", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "AGE_METHOD"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_demo_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "select", "widget-id": "gender", "widget-type": "input", "widget-label": "Gender", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.gender", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "GENDER"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "marital_status", "widget-type": "input", "widget-label": "Marital Status", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.marital_status", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "MARITAL_STATUS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "citizenship_category", "widget-type": "input", "widget-label": "Citizenship Category", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.citizenship_category", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "CITIZENSHIP_CATEGORY"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_demo_3", "panel-orientation": "vertical"}], "panel-id": "panel_demographic_details_main", "panel-orientation": "horizontal"}], "section-id": "individual_demographic_details", "section-title": "demographic_details", "section-editable": true, "section-supporting-documents": []}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_disability_section',
    'b86d5423-0d7f-44af-9877-7cfa8b90b285',
    'FALSE',
    'individual_disability',
    'Individual Disability',
    'FALSE',
    0,
    'TRUE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "table", "widget-id": "individual_disability_table", "widget-type": "table", "widget-label": "Disability Details", "widget-readonly": false, "widget-data-path": "b86d5423-0d7f-44af-9877-7cfa8b90b285.records", "widget-data-columns": [{"widget": "select", "column-key": "disability_domains", "widget-type": "input", "widget-label": "Disability Domain", "widget-data-path": "disability_domains", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "DISABILITY_DOMAIN"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "column-key": "disability_severity", "widget-type": "input", "widget-label": "Severity", "widget-data-path": "disability_severity", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "DISABILITY_SEVERITY"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "widget-data-add-label": "Add Disability", "widget-data-operations": {"add": true, "edit": true, "remove": true}}], "panel-id": "vertical_panel_individual_disability", "panel-column-span": 3, "panel-orientation": "vertical"}], "panel-id": "horizontal_panel_individual_disability", "panel-orientation": "horizontal"}], "section-id": "individual_disability", "section-title": "individual_disability", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_header_info_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'header_info',
    NULL,
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "header-section", "widget-id": "registry-header", "widget-type": "group", "widget-data-path": {"name": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.record_name", "image": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.record_image_storage_id", "status": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.record_status", "createdAt": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.created_at", "createdBy": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.created_by", "idealScore": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.ideal_score", "functionalId": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.functional_record_id", "statusReason": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.record_status_reason", "lastApprovedAt": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.last_approved_at", "lastApprovedBy": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.last_approved_by", "completionScore": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.actual_score"}, "widget-data-format": {"imageSize": 120, "nameColor": "#ED7C22", "statusColors": {"ACTIVE": "#16A34A", "ARCHIVED": "#6B7280", "INACTIVE": "#D97706"}}, "widget-field-config": {"status": {"data-source": {"type": "static", "options": [{"label": "ACTIVE", "value": "ACTIVE"}, {"label": "INACTIVE", "value": "INACTIVE"}, {"label": "ARCHIVED", "value": "ARCHIVED"}]}}}}], "panel-id": "individual_header_inside_panel", "panel-orientation": "vertical"}], "panel-id": "individual_header_outside_panel", "panel-orientation": "horizontal"}], "section-id": "individual_header", "section-title": "", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_land_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_land',
    'Individual Land',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "boolean", "widget-id": "land_access", "widget-type": "input", "widget-label": "Land Access", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.land_access"}], "panel-id": "panel_land_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "number", "widget-id": "land_size", "widget-type": "input", "widget-label": "Land Size(hectare)", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.land_size", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 3}, "widget-data-options": {"action": "enable", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.land_access", "value": true, "operator": "equals"}}, "widget-data-validation": {"min": 0.01, "required": {"condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.land_access", "value": true, "operator": "equals"}}}}], "panel-id": "panel_land_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "multi-select", "widget-id": "productive_assets", "widget-type": "input", "widget-label": "Productive Assets", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.productive_assets", "widget-data-source": {"type": "static", "options": [{"label": "PLOUGH", "value": "PLOUGH"}, {"label": "IRRIGATION_PUMP", "value": "IRRIGATION_PUMP"}, {"label": "OTHER", "value": "OTHER"}]}, "widget-data-options": {"action": "enable", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.land_access", "value": true, "operator": "equals"}}}], "panel-id": "panel_land_3", "panel-orientation": "vertical"}], "panel-id": "panel_land_main", "panel-orientation": "horizontal"}], "section-id": "individual_land", "section-title": "individual_land", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_livestock_section',
    '2893d571-e350-4bfd-baaa-82f8f53c5f0a',
    'FALSE',
    'livestock',
    'Individual Livestock',
    'FALSE',
    0,
    'TRUE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "table", "widget-id": "individual_livestock_table", "widget-type": "table", "widget-label": "Livestock", "widget-readonly": false, "widget-data-path": "2893d571-e350-4bfd-baaa-82f8f53c5f0a.records", "widget-data-columns": [{"widget": "select", "column-key": "livestock_species", "widget-type": "input", "widget-label": "Species", "widget-data-path": "livestock_species", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "LIVESTOCK_SPECIES"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "column-key": "livestock_counts", "widget-type": "input", "widget-label": "Count Band", "widget-data-path": "livestock_counts", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "LIVESTOCK_COUNT_BAND"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "widget-data-add-label": "Add Livestock", "widget-data-operations": {"add": true, "edit": true, "remove": true}}], "panel-id": "vertical_panel_individual_livestock", "panel-column-span": 3, "panel-orientation": "vertical"}], "panel-id": "horizontal_panel_individual_livestock", "panel-orientation": "horizontal"}], "section-id": "individual_livestock", "section-title": "livestock", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_programs_section',
    '4bd46bad-d06d-421c-937f-70c31d3148db',
    'FALSE',
    'individual_programs',
    'Individual Programs',
    'FALSE',
    0,
    'TRUE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "table", "widget-id": "individual_programs_table", "widget-type": "table", "widget-label": "Program Enrollments", "widget-readonly": false, "widget-data-path": "4bd46bad-d06d-421c-937f-70c31d3148db.records", "widget-data-columns": [{"widget": "text", "column-key": "program_id", "widget-type": "input", "widget-label": "Program ID", "widget-data-path": "program_id"}, {"widget": "select", "column-key": "program_name", "widget-type": "input", "widget-label": "Program Name", "widget-data-path": "program_name", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "PROGRAM"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "date", "column-key": "program_start_date", "widget-type": "input", "widget-label": "Start Date", "widget-data-path": "program_start_date", "widget-data-options": {"maxDate": "today"}}, {"widget": "date", "column-key": "program_exit_date", "widget-type": "input", "widget-label": "Exit Date", "widget-data-path": "program_exit_date", "widget-data-options": {"minDateField": "program_start_date", "minDateMessage": "Exit date must be on or after the start date"}}], "widget-data-add-label": "Add Program", "widget-data-operations": {"add": true, "edit": true, "remove": true}}], "panel-id": "vertical_panel_individual_programs", "panel-column-span": 3, "panel-orientation": "vertical"}], "panel-id": "horizontal_panel_individual_programs", "panel-orientation": "horizontal"}], "section-id": "individual_programs", "section-title": "individual_programs", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_registration_identifier_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_identifier',
    'Identifier',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "boolean", "widget-id": "has_national_id", "widget-type": "input", "widget-label": "Do you have National ID?", "widget-required": true, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.has_national_id", "widget-data-format": {"allowUnset": false, "booleanControlType": "radio", "booleanRepresentation": "yes-no"}, "widget-orientation": "horizontal"}], "panel-id": "panel_reg_id_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "foundation_id", "widget-type": "input", "widget-label": "Fayda ID", "widget-readonly": false, "widget-required": true, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.foundational_id", "widget-data-options": {"action": "show", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.has_national_id", "value": true, "operator": "equals"}}, "widget-data-validation": {"pattern": "^[0-9]*$", "maxLength": 16, "minLength": 12, "patternMessage": "Only digits are allowed"}}], "panel-id": "panel_reg_id_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "rid", "widget-type": "input", "widget-label": "RID", "widget-readonly": false, "widget-required": true, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.rid", "widget-data-options": {"action": "show", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.has_national_id", "value": false, "operator": "equals"}}, "widget-data-validation": {"pattern": "^[0-9]*$", "maxLength": 29, "minLength": 29, "patternMessage": "Only digits are allowed"}}], "panel-id": "panel_reg_id_3", "panel-orientation": "vertical"}], "panel-id": "panel_registration_identifier_main", "panel-orientation": "horizontal"}], "section-id": "individual_registration_identifier", "section-title": "identifier", "section-editable": true, "section-supporting-documents": []}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_scores_section',
    'c51e60ca-9990-4077-8d62-0b414ea7e66d',
    'FALSE',
    'individual_computation_scores',
    'Computation Scores',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "scores-display", "widget-id": "record-scores", "widget-type": "group", "widget-readonly": true, "widget-data-path": "c51e60ca-9990-4077-8d62-0b414ea7e66d.records"}], "panel-id": "vertical_panel_scores", "panel-column-span": 3, "panel-orientation": "vertical"}], "panel-id": "horizontal_panel_scores", "panel-orientation": "horizontal"}], "section-id": "register_scores", "section-title": "computation_scores", "section-editable": false}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_vulnerability_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_vulnerability',
    'Individual Vulnerability',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "boolean", "widget-id": "orphanhood_flag", "widget-type": "input", "widget-label": "Orphanhood Flag", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.orphanhood_flag"}, {"widget": "boolean", "widget-id": "chronic_illness_flag", "widget-type": "input", "widget-label": "Chronic Illness Flag", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.chronic_illness_flag", "widget-data-format": {"allowUnset": false, "booleanControlType": "radio", "booleanRepresentation": "yes-no"}, "widget-orientation": "horizontal", "widget-data-default": null, "widget-data-validation": {}}], "panel-id": "panel_vuln_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "select", "widget-id": "displacement_status", "widget-type": "input", "widget-label": "Displacement Status", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.displacement_status", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "DISPLACEMENT_STATUS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "pastoralist_classification", "widget-type": "input", "widget-label": "Pastoralist Classification", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.pastoralist_classification", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "PASTORALIST_CLASSIFICATION"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "boolean", "widget-id": "high_mobility_indicator_p", "widget-type": "input", "widget-label": "High Mobility Indicator", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.high_mobility_indicator", "widget-data-options": {"action": "show", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.pastoralist_classification", "value": "PASTORALIST", "operator": "equals"}}}, {"widget": "boolean", "widget-id": "high_mobility_indicator_sp", "widget-type": "input", "widget-label": "High Mobility Indicator", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.high_mobility_indicator", "widget-data-options": {"action": "show", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.pastoralist_classification", "value": "SEMI_PASTORALIST", "operator": "equals"}}}], "panel-id": "panel_vuln_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "boolean", "widget-id": "plw_status", "widget-type": "input", "widget-label": "PLW Status", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.plw_status"}, {"widget": "date", "widget-id": "plw_date", "widget-type": "input", "widget-label": "PLW Date", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.plw_date", "widget-data-options": {"action": "show", "maxDate": "today", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.plw_status", "value": true, "operator": "equals"}}}], "panel-id": "panel_vuln_3", "panel-orientation": "vertical"}], "panel-id": "panel_vulnerability_main", "panel-orientation": "horizontal"}], "section-id": "individual_vulnerability", "section-title": "individual_vulnerability", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_vulnerability_intake_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_vulnerability_intake',
    'Individual Vulnerability Intake',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "boolean", "widget-id": "orphanhood_flag", "widget-type": "input", "widget-label": "Orphanhood Flag", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.orphanhood_flag"}, {"widget": "boolean", "widget-id": "chronic_illness_flag", "widget-type": "input", "widget-label": "Chronic Illness Flag", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.chronic_illness_flag", "widget-data-format": {"allowUnset": false, "booleanControlType": "radio", "booleanRepresentation": "yes-no"}, "widget-orientation": "horizontal", "widget-data-default": null, "widget-data-validation": {}}], "panel-id": "panel_vuln_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "select", "widget-id": "displacement_status", "widget-type": "input", "widget-label": "Displacement Status", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.displacement_status", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "DISPLACEMENT_STATUS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "pastoralist_classification", "widget-type": "input", "widget-label": "Pastoralist Classification", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.pastoralist_classification", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "PASTORALIST_CLASSIFICATION"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "boolean", "widget-id": "high_mobility_indicator_p", "widget-type": "input", "widget-label": "High Mobility Indicator", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.high_mobility_indicator", "widget-data-options": {"action": "show", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.pastoralist_classification", "value": "PASTORALIST", "operator": "equals"}}}, {"widget": "boolean", "widget-id": "high_mobility_indicator_sp", "widget-type": "input", "widget-label": "High Mobility Indicator", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.high_mobility_indicator", "widget-data-options": {"action": "show", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.pastoralist_classification", "value": "SEMI_PASTORALIST", "operator": "equals"}}}], "panel-id": "panel_vuln_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "boolean", "widget-id": "plw_status", "widget-type": "input", "widget-label": "PLW Status", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.plw_status"}, {"widget": "date", "widget-id": "plw_date", "widget-type": "input", "widget-label": "PLW Date", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.plw_date", "widget-data-options": {"action": "show", "maxDate": "today", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.plw_status", "value": true, "operator": "equals"}}}], "panel-id": "panel_vuln_3", "panel-orientation": "vertical"}], "panel-id": "panel_vulnerability_main", "panel-orientation": "horizontal"}], "section-id": "individual_vulnerability", "section-title": "individual_vulnerability", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_household_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_household',
    'Individual Household',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "register-lookup", "widget-id": "household_lookup", "widget-type": "input", "widget-label": "Household", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.link_internal_record_id", "widget-data-source": {"type": "api", "method": "POST", "params": {"register_id": "9055ab43-c85d-4833-bd00-ca657bb72644"}, "service": "register", "endpoint": "records"}, "widget-lookup-config": {"page_size": 10, "action_label": "Click to Search Household", "search_placeholder": "Search by name or ID...", "select_record_label": "Select Household"}}], "panel-id": "household_lookup_inside_panel", "panel-orientation": "vertical"}], "panel-id": "household_lookup_outside_panel", "panel-orientation": "horizontal"}], "section-id": "household_lookup", "section-title": "Household", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_member_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'household_members',
    'Household Members',
    'FALSE',
    0,
    'TRUE',
    10,
    '{"panels": [{"widgets": [{"widget": "dialog-table", "widget-id": "members_table", "widget-type": "table", "widget-label": "Household Member Records", "widget-readonly": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.records", "panel-column-span": 12, "panel-orientation": "vertical", "widget-data-columns": [{"widget": "boolean", "column-key": "has_national_id", "widget-type": "input", "widget-label": "Do you have National ID?", "widget-required": true, "widget-data-path": "has_national_id", "widget-data-format": {"allowUnset": false, "booleanControlType": "radio", "booleanRepresentation": "yes-no"}, "widget-orientation": "horizontal"}, {"widget": "text", "column-key": "foundational_id", "widget-type": "input", "widget-label": "Fayda ID", "widget-required": false, "widget-data-path": "foundational_id", "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "has_national_id", "value": true, "operator": "equals"}}, {"action": "require", "condition": {"field": "has_national_id", "value": true, "operator": "equals"}}]}, "widget-data-validation": {"pattern": "^[0-9]*$", "maxLength": 16, "minLength": 12, "patternMessage": "Only digits are allowed"}}, {"widget": "text", "column-key": "rid", "widget-type": "input", "widget-label": "RID", "widget-required": false, "widget-data-path": "rid", "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "has_national_id", "value": false, "operator": "equals"}}, {"action": "require", "condition": {"field": "has_national_id", "value": false, "operator": "equals"}}]}, "widget-data-validation": {"pattern": "^[0-9]*$", "maxLength": 29, "minLength": 29, "patternMessage": "Only digits are allowed"}}, {"widget": "select", "column-key": "prefix", "widget-type": "input", "widget-label": "Prefix", "widget-required": true, "widget-data-path": "prefix", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "PREFIX"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "text", "column-key": "first_name", "widget-type": "input", "widget-label": "First Name", "widget-required": true, "widget-data-path": "first_name", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F .\\/''-]+$", "maxLength": 50, "minLength": 2, "patternMessage": "Only letters, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}, {"widget": "text", "column-key": "middle_name", "widget-type": "input", "widget-label": "Middle Name", "widget-required": true, "widget-data-path": "middle_name", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F .\\/''-]+$", "maxLength": 50, "minLength": 2, "patternMessage": "Only letters, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}, {"widget": "text", "column-key": "last_name", "widget-type": "input", "widget-label": "Last Name", "widget-required": true, "widget-data-path": "last_name", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F .\\/''-]+$", "maxLength": 50, "minLength": 2, "patternMessage": "Only letters, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}, {"widget": "date", "column-key": "birth_date", "widget-type": "input", "widget-label": "Birth Date", "widget-required": true, "widget-data-path": "birth_date", "widget-data-options": {"maxDate": "today"}}, {"widget": "select", "column-key": "gender", "widget-type": "input", "widget-label": "Gender", "widget-required": true, "widget-data-path": "gender", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "GENDER"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "boolean", "column-key": "is_head", "widget-type": "input", "widget-label": "Is Head of Household", "widget-required": false, "widget-data-path": "is_head", "widget-data-format": {"allowUnset": false, "booleanControlType": "radio", "booleanRepresentation": "yes-no"}, "widget-orientation": "horizontal", "widget-data-default": null}, {"widget": "select", "column-key": "relationship_to_head", "widget-type": "input", "widget-label": "Relationship to Head", "widget-required": false, "widget-data-path": "relationship_to_head", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "RELATIONSHIP_TO_HEAD"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}, "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "is_head", "value": false, "operator": "equals"}}, {"action": "hide", "condition": {"field": "is_head", "value": true, "operator": "equals"}}]}}], "widget-data-add-label": "Add Member", "widget-data-operations": {"add": true, "edit": true, "remove": true}}], "panel-id": "panel_household_members"}], "section-id": "household_members_section", "section-title": "Household Members", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_household_relationship_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'relationship_to_household_head',
    'Relationship to Household Head',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "boolean", "widget-id": "is_head", "widget-type": "input", "widget-label": "Is Head", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.is_head", "widget-data-format": {"allowUnset": false, "booleanControlType": "radio", "booleanRepresentation": "yes-no"}, "widget-orientation": "horizontal", "widget-data-default": null}], "panel-id": "panel_hh_rel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "select", "widget-id": "relationship_to_head", "widget-type": "input", "widget-label": "Relationship to Head", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.relationship_to_head", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "RELATIONSHIP_TO_HEAD"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}, "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.is_head", "value": false, "operator": "equals"}}, {"action": "hide", "condition": {"field": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.is_head", "value": true, "operator": "equals"}}]}}, {"widget": "select", "widget-id": "residency_status", "widget-type": "input", "widget-label": "Residency Status", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.residency_status", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "RESIDENCY_STATUS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "panel_hh_rel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "boolean", "widget-id": "dependency_indicator", "widget-type": "input", "widget-label": "Dependency Indicator", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.dependency_indicator"}], "panel-id": "panel_hh_rel_3", "panel-orientation": "vertical"}], "panel-id": "panel_household_relationship_main", "panel-orientation": "horizontal"}], "section-id": "individual_household_relationship", "section-title": "relationship_to_household_head", "section-editable": true, "section-supporting-documents": []}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    '1bb00ea5-856f-4ba7-bfb1-086d63ed2e68',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_attachment',
    'Attachments for Household',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"widgets": [{"widget": "docs", "documents": [{"document-key": "attachment_one", "document-label": "attachment_one", "document-accept": ".pdf,.jpg,.jpeg,.png", "document-max-size": 5242880, "document-required": false}, {"document-key": "attachment_two", "document-label": "attachment_two", "document-accept": ".pdf,.jpg,.jpeg,.png", "document-max-size": 5242880, "document-required": false}, {"document-key": "attachment_three", "document-label": "attachment_three", "document-accept": ".pdf,.jpg,.jpeg,.png", "document-max-size": 5242880}, {"document-key": "attachment_four", "document-label": "attachment_four", "document-accept": ".pdf,.jpg,.jpeg,.png", "document-max-size": 5242880}, {"document-key": "attachment_five", "document-label": "attachment_five", "document-accept": ".pdf,.jpg,.jpeg,.png", "document-max-size": 2097152}, {"document-key": "attachment_six", "document-label": "attachment_six", "document-accept": ".pdf,.jpg,.jpeg,.png", "document-max-size": 2097152}], "widget-id": "household_docs", "widget-type": "input", "widget-label": "Supporting Documents", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.documents", "widget-total-docs": 6}], "panel-id": "panel_docs_main"}], "section-id": "household_documents", "section-title": "household_documents", "section-editable": true, "section-column-span": 3}',
    'FALSE',
    'FALSE',
    'FALSE',
    'FALSE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_location_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_location_details',
    'Location Details',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "geo-hierarchy", "widget-id": "individual_geo_hierarchy", "widget-type": "input", "widget-label": "Location Hierarchy", "widget-required": true, "widget-data-path": {"value": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.geo_lowest_level_value_id", "hierarchy": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.geo_code_hierarchy_json"}, "widget-geo-layout": {"columnSpan": 1}, "widget-data-source": {"type": "api", "method": "POST", "service": "master-data", "levelsEndpoint": "get-all-g2p-geo-levels", "valuesEndpoint": "geo-level-values"}}], "panel-id": "panel_geo_main", "panel-column-span": 1, "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "kebele_code", "widget-type": "input", "widget-label": "Kebele", "widget-readonly": false, "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.kebele_code", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F0-9 .\\/''-]+$", "maxLength": 50, "patternMessage": "Only letters, numbers, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}, {"widget": "text", "widget-id": "locality_ea_code", "widget-type": "input", "widget-label": "Locality / EA Code", "widget-readonly": false, "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.locality_ea_code", "widget-data-validation": {"pattern": "^[A-Za-zÀ-ÿ\\u0900-\\u097F0-9 .\\/''-]+$", "maxLength": 50, "patternMessage": "Only letters, numbers, spaces, apostrophes, hyphens, dots, and slashes are allowed"}}, {"widget": "textarea", "widget-id": "address_descriptor", "widget-type": "input", "widget-label": "Address Descriptor", "widget-readonly": false, "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.address_descriptor", "widget-data-format": {"rows": 2, "caseControl": "none", "characterType": "any", "showCharCounter": true}, "widget-data-validation": {"maxLength": 500, "minLength": 6}, "widget-data-placeholder": "Enter address descriptor"}], "panel-id": "panel_location_2", "panel-column-span": 1, "panel-orientation": "vertical"}, {"widgets": [{"widget": "number", "widget-id": "gps_latitude", "widget-type": "input", "widget-label": "GPS Latitude", "widget-readonly": false, "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.gps_latitude", "widget-data-format": {"textAlign": "right", "allowSigned": true, "numericType": "decimal", "formatOnBlur": true, "roundingMode": "round", "decimalPlaces": 6, "decimalSeparator": ".", "thousandSeparator": ","}, "widget-data-validation": {"max": 90, "min": -90, "pattern": "^[0-9]+(\\.[0-9]{1,2})?$", "patternMessage": "Invalid number format"}, "widget-data-placeholder": "Enter latitude"}, {"widget": "number", "widget-id": "gps_longitude", "widget-type": "input", "widget-label": "GPS Longitude", "widget-readonly": false, "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.gps_longitude", "widget-data-format": {"textAlign": "right", "allowSigned": true, "numericType": "decimal", "formatOnBlur": true, "roundingMode": "round", "decimalPlaces": 6, "decimalSeparator": ".", "thousandSeparator": ","}, "widget-data-validation": {"max": 180, "min": -180, "pattern": "^[0-9]+(\\.[0-9]{1,2})?$", "patternMessage": "Invalid number format"}, "widget-data-placeholder": "Enter longitude"}, {"widget": "number", "widget-id": "gps_accuracy", "widget-type": "input", "widget-label": "GPS Accuracy", "widget-readonly": false, "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.gps_accuracy", "widget-data-format": {"textAlign": "right", "allowSigned": true, "numericType": "decimal", "formatOnBlur": true, "roundingMode": "round", "decimalPlaces": 6, "decimalSeparator": ".", "thousandSeparator": ","}, "widget-data-validation": {"max": 10000, "min": 0, "pattern": "^[0-9]+(\\.[0-9]{1,2})?$", "patternMessage": "Invalid number format"}, "widget-data-placeholder": "Enter GPS accuracy"}], "panel-id": "panel_location_3", "panel-column-span": 1, "panel-orientation": "vertical"}], "panel-id": "panel_location_details_main", "panel-orientation": "horizontal"}], "section-id": "individual_location_details", "section-title": "location_details", "section-editable": true, "section-column-span": 3, "section-supporting-documents": []}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'village_header_info_section',
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'FALSE',
    'village_header_info',
    'Village Header Info',
    'FALSE',
    0,
    'FALSE',
    10,
    '{"panels": [{"panels": [{"widgets": [{"widget": "header-section", "widget-id": "registry-header", "widget-type": "group", "widget-data-path": {"name": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.record_name", "image": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.record_image_storage_id", "status": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.record_status", "createdAt": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.created_at", "createdBy": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.created_by", "idealScore": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.ideal_score", "functionalId": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.functional_record_id", "statusReason": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.record_status_reason", "lastApprovedAt": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.last_approved_at", "lastApprovedBy": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.last_approved_by", "completionScore": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.actual_score"}, "widget-data-format": {"imageSize": 120, "nameColor": "#0B6E4F", "statusColors": {"ACTIVE": "#16A34A", "ARCHIVED": "#6B7280", "INACTIVE": "#D97706"}}, "widget-field-config": {"status": {"data-source": {"type": "static", "options": [{"label": "ACTIVE", "value": "ACTIVE"}, {"label": "INACTIVE", "value": "INACTIVE"}, {"label": "ARCHIVED", "value": "ARCHIVED"}]}}}}], "panel-id": "village_header_inside_panel", "panel-orientation": "vertical"}], "panel-id": "village_header_outside_panel", "panel-orientation": "horizontal"}], "section-id": "village_header", "section-title": "", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'village_identity_section',
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'FALSE',
    'village_identity',
    'Village Identity',
    'FALSE',
    0,
    'FALSE',
    20,
    '{"panels": [{"panels": [{"widgets": [{"widget": "text", "widget-id": "village_code", "widget-type": "input", "widget-label": "Village Code", "widget-required": true, "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.village_code"}, {"widget": "text", "widget-id": "village_name", "widget-type": "input", "widget-label": "Village Name", "widget-required": true, "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.village_name"}, {"widget": "text", "widget-id": "region", "widget-type": "input", "widget-label": "Region", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.region"}, {"widget": "text", "widget-id": "district", "widget-type": "input", "widget-label": "District", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.district"}, {"widget": "text", "widget-id": "subcounty", "widget-type": "input", "widget-label": "Subcounty", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.subcounty"}, {"widget": "text", "widget-id": "parish", "widget-type": "input", "widget-label": "Parish", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.parish"}], "panel-id": "village_identity_inside", "panel-orientation": "vertical"}], "panel-id": "village_identity_outside", "panel-orientation": "horizontal"}], "section-id": "village_identity", "section-title": "Village Identity", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'village_leadership_section',
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'FALSE',
    'village_leadership',
    'Village Leadership & Grant',
    'FALSE',
    0,
    'FALSE',
    30,
    '{"panels": [{"panels": [{"widgets": [{"widget": "text", "widget-id": "chairperson_name", "widget-type": "input", "widget-label": "Chairperson Name", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.chairperson_name"}, {"widget": "text", "widget-id": "chairperson_phone", "widget-type": "input", "widget-label": "Chairperson Phone", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.chairperson_phone"}, {"widget": "text", "widget-id": "grant_status", "widget-type": "input", "widget-label": "Grant Status", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.grant_status"}, {"widget": "text", "widget-id": "sacco_name", "widget-type": "input", "widget-label": "SACCO Name", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.sacco_name"}, {"widget": "text", "widget-id": "bank_name", "widget-type": "input", "widget-label": "Bank Name", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.bank_name"}, {"widget": "text", "widget-id": "bank_account_number", "widget-type": "input", "widget-label": "Bank Account", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.bank_account_number"}, {"widget": "number", "widget-id": "household_count", "widget-type": "input", "widget-label": "Household Count", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.household_count"}, {"widget": "number", "widget-id": "population_estimate", "widget-type": "input", "widget-label": "Population Estimate", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.population_estimate"}], "panel-id": "village_leadership_inside", "panel-orientation": "vertical"}], "panel-id": "village_leadership_outside", "panel-orientation": "horizontal"}], "section-id": "village_leadership", "section-title": "Leadership & Grant", "section-editable": true}',
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  );