INSERT INTO
    "public"."g2p_intake_form_ui_tab_sections" (
        "tab_section_id",
        "tab_id",
        "section_id",
        "section_order"
    )
VALUES
    (
        'vsss-intake-sec-ind-identity',
        't2',
        'individual_identity_section',
        1
    ),
    (
        'vsss-intake-sec-ind-location',
        't2',
        'individual_location_section',
        2
    ),
    (
        'vsss-intake-sec-ind-bank',
        't2',
        'individual_bank_section',
        3
    ),
    (
        'vsss-intake-sec-hh-identity',
        't1',
        'household_identity_section',
        1
    ),
    (
        'vsss-intake-sec-hh-location',
        't1',
        'household_location_section',
        2
    ),
    (
        'vsss-intake-sec-hh-financial',
        't1',
        'household_financial_section',
        3
    ),
    (
        'vsss-intake-sec-hh-bank',
        't1',
        'household_bank_section',
        4
    ),
    (
        'vsss-intake-sec-hh-capacity',
        't1',
        'household_capacity_section',
        5
    ),
    (
        'vsss-intake-sec-village-ident-001',
        'village_intake_tab',
        'village_identity_section',
        1
    ),
    (
        'vsss-intake-sec-village-location',
        'village_intake_tab',
        'village_location_section',
        2
    ),
    (
        'vsss-intake-sec-village-lead-001',
        'village_intake_tab',
        'village_leadership_section',
        3
    ),
    (
        'vsss-intake-sec-ind-household',
        't2',
        'individual_household_section',
        4
    ),
    (
        'vsss-intake-sec-ind-documents',
        't2',
        'individual_attachment_section',
        5
    ),
    (
        'vsss-intake-sec-hh-members',
        't1',
        'household_member_section',
        6
    ),
    (
        'vsss-intake-sec-hh-village',
        't1',
        'household_village_section',
        7
    ),
    (
        'vsss-intake-sec-hh-documents',
        't1',
        'household_attachment_section',
        8
    ),
    (
        'vsss-intake-sec-village-households',
        'village_intake_tab',
        'village_household_section',
        4
    ),
    (
        'vsss-intake-sec-village-documents',
        'village_intake_tab',
        'village_attachment_section',
        5
    );
