INSERT INTO
  "public"."g2p_register_sections" (
    "register_id",
    "section_id",
    "section_register_id",
    "is_core_section",
    "section_mnemonic",
    "section_description",
    "documents_required",
    "no_of_verifications_required",
    "is_list",
    "section_weightage",
    "section_ui_schema",
    "cr_auto_approve_for_bene_portal",
    "cr_auto_approve_for_agent_portal",
    "cr_auto_approve_for_staff_portal",
    "cr_auto_approve_for_partner"
  )
VALUES
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_header_info_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_header_info',
    'Individual Header Info',
    'FALSE',
    0,
    'FALSE',
    1,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "header-section", "widget-id": "registry-header", "widget-type": "group", "widget-data-path": {"name": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.record_name", "image": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.record_image_storage_id", "status": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.record_status", "createdAt": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.created_at", "createdBy": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.created_by", "functionalId": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.functional_record_id", "statusReason": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.record_status_reason", "lastApprovedAt": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.last_approved_at", "lastApprovedBy": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.last_approved_by"}, "widget-data-format": {"imageSize": 120, "nameColor": "#ED7C22", "statusColors": {"ACTIVE": "#16A34A", "ARCHIVED": "#6B7280", "INACTIVE": "#D97706"}}, "widget-field-config": {"status": {"data-source": {"type": "static", "options": [{"label": "ACTIVE", "value": "ACTIVE"}, {"label": "INACTIVE", "value": "INACTIVE"}, {"label": "ARCHIVED", "value": "ARCHIVED"}]}}}}], "panel-id": "individual_header_inside", "panel-orientation": "vertical"}], "panel-id": "individual_header_outside", "panel-orientation": "horizontal"}], "section-id": "individual_header", "section-title": "", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_identity_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_identity',
    'Individual Identity',
    'FALSE',
    0,
    'FALSE',
    10,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "text", "widget-id": "first_name", "widget-type": "input", "widget-label": "First Name", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.first_name", "widget-required": true}, {"widget": "text", "widget-id": "middle_name", "widget-type": "input", "widget-label": "Middle Name", "widget-required": true, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.middle_name"}, {"widget": "text", "widget-id": "last_name", "widget-type": "input", "widget-label": "Last Name", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.last_name", "widget-required": true}], "panel-id": "individual_identity_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "additional_name", "widget-type": "input", "widget-label": "Additional Name", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.additional_name"}, {"widget": "date", "widget-id": "birth_date", "widget-type": "input", "widget-label": "Birthdate", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.birth_date"}], "panel-id": "individual_identity_panel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "select", "widget-id": "gender", "widget-type": "input", "widget-label": "Gender", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.gender", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "GENDER"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "text", "widget-id": "phone", "widget-type": "input", "widget-label": "Phone", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.phone"}], "panel-id": "individual_identity_panel_3", "panel-orientation": "vertical"}], "panel-id": "individual_identity_outer", "panel-orientation": "horizontal"}], "section-id": "individual_identity", "section-title": "Identity", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_location_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_location',
    'Individual Administrative Location',
    'FALSE',
    0,
    'FALSE',
    20,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "geo-hierarchy", "widget-id": "individual_geo_hierarchy", "widget-type": "input", "widget-label": "Location Hierarchy", "widget-required": true, "widget-data-path": {"value": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.geo_lowest_level_value_id", "hierarchy": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.geo_code_hierarchy_json"}, "widget-geo-layout": {"columnSpan": 1}, "widget-data-source": {"type": "api", "method": "POST", "service": "master-data", "levelsEndpoint": "get-all-g2p-geo-levels", "valuesEndpoint": "geo-level-values"}}], "panel-id": "individual_location_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "polling_station", "widget-type": "input", "widget-label": "Polling Station", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.polling_station"}], "panel-id": "individual_location_panel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "number", "widget-id": "gps_latitude", "widget-type": "input", "widget-label": "GPS Latitude", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.gps_latitude", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 6}}, {"widget": "number", "widget-id": "gps_longitude", "widget-type": "input", "widget-label": "GPS Longitude", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.gps_longitude", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 6}}], "panel-id": "individual_location_panel_3", "panel-orientation": "vertical"}], "panel-id": "individual_location_outer", "panel-orientation": "horizontal"}], "section-id": "individual_location", "section-title": "Administrative Location", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_bank_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_bank',
    'Individual Bank Details',
    'FALSE',
    0,
    'FALSE',
    30,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "boolean", "widget-id": "has_sacco_account", "widget-type": "input", "widget-label": "Has SACCO Account", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.has_sacco_account"}], "panel-id": "individual_bank_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "bank_name", "widget-type": "input", "widget-label": "Bank Name", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.bank_name"}], "panel-id": "individual_bank_panel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "bank_account_number", "widget-type": "input", "widget-label": "Bank Account Number", "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.bank_account_number"}], "panel-id": "individual_bank_panel_3", "panel-orientation": "vertical"}], "panel-id": "individual_bank_outer", "panel-orientation": "horizontal"}], "section-id": "individual_bank", "section-title": "Bank Details", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_header_info_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_header_info',
    'Household Header Info',
    'FALSE',
    0,
    'FALSE',
    1,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "header-section", "widget-id": "registry-header", "widget-type": "group", "widget-data-path": {"name": "9055ab43-c85d-4833-bd00-ca657bb72644.record_name", "image": "9055ab43-c85d-4833-bd00-ca657bb72644.record_image_storage_id", "status": "9055ab43-c85d-4833-bd00-ca657bb72644.record_status", "createdAt": "9055ab43-c85d-4833-bd00-ca657bb72644.created_at", "createdBy": "9055ab43-c85d-4833-bd00-ca657bb72644.created_by", "functionalId": "9055ab43-c85d-4833-bd00-ca657bb72644.functional_record_id", "statusReason": "9055ab43-c85d-4833-bd00-ca657bb72644.record_status_reason", "lastApprovedAt": "9055ab43-c85d-4833-bd00-ca657bb72644.last_approved_at", "lastApprovedBy": "9055ab43-c85d-4833-bd00-ca657bb72644.last_approved_by"}, "widget-data-format": {"imageSize": 120, "nameColor": "#ED7C22", "statusColors": {"ACTIVE": "#16A34A", "ARCHIVED": "#6B7280", "INACTIVE": "#D97706"}}, "widget-field-config": {"status": {"data-source": {"type": "static", "options": [{"label": "ACTIVE", "value": "ACTIVE"}, {"label": "INACTIVE", "value": "INACTIVE"}, {"label": "ARCHIVED", "value": "ARCHIVED"}]}}}}], "panel-id": "household_header_inside", "panel-orientation": "vertical"}], "panel-id": "household_header_outside", "panel-orientation": "horizontal"}], "section-id": "household_header", "section-title": "", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_identity_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_identity',
    'Household Identity',
    'FALSE',
    0,
    'FALSE',
    10,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "text", "widget-id": "name", "widget-type": "input", "widget-label": "Name", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.name", "widget-required": true}], "panel-id": "household_identity_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "number", "widget-id": "household_size", "widget-type": "input", "widget-label": "Household Size", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.household_size", "widget-data-format": {"allowSigned": false, "numericType": "integer"}}], "panel-id": "household_identity_panel_2", "panel-orientation": "vertical"}, {"widgets": [], "panel-id": "household_identity_panel_3", "panel-orientation": "vertical"}], "panel-id": "household_identity_outer", "panel-orientation": "horizontal"}], "section-id": "household_identity", "section-title": "Identity", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_location_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_location',
    'Household Administrative Location',
    'FALSE',
    0,
    'FALSE',
    20,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "geo-hierarchy", "widget-id": "household_geo_hierarchy", "widget-type": "input", "widget-label": "Location Hierarchy", "widget-required": true, "widget-data-path": {"value": "9055ab43-c85d-4833-bd00-ca657bb72644.geo_lowest_level_value_id", "hierarchy": "9055ab43-c85d-4833-bd00-ca657bb72644.geo_code_hierarchy_json"}, "widget-geo-layout": {"columnSpan": 1}, "widget-data-source": {"type": "api", "method": "POST", "service": "master-data", "levelsEndpoint": "get-all-g2p-geo-levels", "valuesEndpoint": "geo-level-values"}}], "panel-id": "household_location_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "polling_station", "widget-type": "input", "widget-label": "Polling Station", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.polling_station"}], "panel-id": "household_location_panel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "number", "widget-id": "gps_latitude", "widget-type": "input", "widget-label": "GPS Latitude", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.gps_latitude", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 6}}, {"widget": "number", "widget-id": "gps_longitude", "widget-type": "input", "widget-label": "GPS Longitude", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.gps_longitude", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 6}}], "panel-id": "household_location_panel_3", "panel-orientation": "vertical"}], "panel-id": "household_location_outer", "panel-orientation": "horizontal"}], "section-id": "household_location", "section-title": "Administrative Location", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_financial_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_financial',
    'Household Financial Mapping',
    'FALSE',
    0,
    'FALSE',
    30,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "text", "widget-id": "bank_name", "widget-type": "input", "widget-label": "Bank Name", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.bank_name"}, {"widget": "text", "widget-id": "branch_name", "widget-type": "input", "widget-label": "Branch Name", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.branch_name"}], "panel-id": "household_financial_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "branch_code", "widget-type": "input", "widget-label": "Branch Code", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.branch_code"}, {"widget": "text", "widget-id": "account_number", "widget-type": "input", "widget-label": "Account Number", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.account_number"}], "panel-id": "household_financial_panel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "ifsc_code", "widget-type": "input", "widget-label": "IFSC Code", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.ifsc_code"}], "panel-id": "household_financial_panel_3", "panel-orientation": "vertical"}], "panel-id": "household_financial_outer", "panel-orientation": "horizontal"}], "section-id": "household_financial", "section-title": "Financial Mapping", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_bank_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_bank',
    'Household Bank Details',
    'FALSE',
    0,
    'FALSE',
    40,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "select", "widget-id": "financial_management", "widget-type": "input", "widget-label": "Financial Management", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.financial_management", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "FINANCIAL_MANAGEMENT"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "household_bank_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "date", "widget-id": "last_disbursement_date", "widget-type": "input", "widget-label": "Last Disbursement Date", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.last_disbursement_date"}], "panel-id": "household_bank_panel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "number", "widget-id": "last_disbursement_amount", "widget-type": "input", "widget-label": "Last Disbursement Amount", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.last_disbursement_amount", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 2}}], "panel-id": "household_bank_panel_3", "panel-orientation": "vertical"}], "panel-id": "household_bank_outer", "panel-orientation": "horizontal"}], "section-id": "household_bank", "section-title": "Bank Details", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_capacity_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_capacity',
    'Household Capacity and Needs',
    'FALSE',
    0,
    'FALSE',
    50,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "select", "widget-id": "training_needs", "widget-type": "input", "widget-label": "Training Needs", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.training_needs", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "TRAINING_NEEDS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "widget-id": "loan_requirement", "widget-type": "input", "widget-label": "Loan Requirement", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.loan_requirement", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "LOAN_REQUIREMENT"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "date", "widget-id": "grand_required_in", "widget-type": "input", "widget-label": "Grant Required In", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.grand_required_in"}], "panel-id": "household_capacity_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "number", "widget-id": "amount_required", "widget-type": "input", "widget-label": "Amount Required", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.amount_required", "widget-data-format": {"allowSigned": false, "numericType": "integer"}}, {"widget": "select", "widget-id": "amount_required_in", "widget-type": "input", "widget-label": "Amount Required In", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.amount_required_in", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "AMOUNT_REQUIRED_IN"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "household_capacity_panel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "boolean", "widget-id": "signed_grant_agreement", "widget-type": "input", "widget-label": "Signed Grant Agreement", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.signed_grant_agreement"}, {"widget": "select", "widget-id": "grant_status", "widget-type": "input", "widget-label": "Grant Status", "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.grant_status", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "GRANT_STATUS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}], "panel-id": "household_capacity_panel_3", "panel-orientation": "vertical"}], "panel-id": "household_capacity_outer", "panel-orientation": "horizontal"}], "section-id": "household_capacity", "section-title": "Capacity & Needs", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'village_header_info_section',
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'FALSE',
    'village_header_info',
    'Village Header Info',
    'FALSE',
    0,
    'FALSE',
    1,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "header-section", "widget-id": "registry-header", "widget-type": "group", "widget-data-path": {"name": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.record_name", "image": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.record_image_storage_id", "status": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.record_status", "createdAt": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.created_at", "createdBy": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.created_by", "functionalId": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.functional_record_id", "statusReason": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.record_status_reason", "lastApprovedAt": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.last_approved_at", "lastApprovedBy": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.last_approved_by"}, "widget-data-format": {"imageSize": 120, "nameColor": "#ED7C22", "statusColors": {"ACTIVE": "#16A34A", "ARCHIVED": "#6B7280", "INACTIVE": "#D97706"}}, "widget-field-config": {"status": {"data-source": {"type": "static", "options": [{"label": "ACTIVE", "value": "ACTIVE"}, {"label": "INACTIVE", "value": "INACTIVE"}, {"label": "ARCHIVED", "value": "ARCHIVED"}]}}}}], "panel-id": "village_header_inside", "panel-orientation": "vertical"}], "panel-id": "village_header_outside", "panel-orientation": "horizontal"}], "section-id": "village_header", "section-title": "", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'village_identity_section',
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'FALSE',
    'village_identity',
    'Village Identity',
    'FALSE',
    0,
    'FALSE',
    10,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "text", "widget-id": "name", "widget-type": "input", "widget-label": "Name", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.name", "widget-required": true}], "panel-id": "village_identity_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "code", "widget-type": "input", "widget-label": "Code", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.code"}], "panel-id": "village_identity_panel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "number", "widget-id": "household_count", "widget-type": "input", "widget-label": "Household Count", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.household_count", "widget-data-format": {"allowSigned": false, "numericType": "integer"}}], "panel-id": "village_identity_panel_3", "panel-orientation": "vertical"}], "panel-id": "village_identity_outer", "panel-orientation": "horizontal"}], "section-id": "village_identity", "section-title": "Identity", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'village_location_section',
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'FALSE',
    'village_location',
    'Village Administrative Location',
    'FALSE',
    0,
    'FALSE',
    20,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "geo-hierarchy", "widget-id": "village_geo_hierarchy", "widget-type": "input", "widget-label": "Location Hierarchy", "widget-required": true, "widget-data-path": {"value": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.geo_lowest_level_value_id", "hierarchy": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.geo_code_hierarchy_json"}, "widget-geo-layout": {"columnSpan": 1}, "widget-data-source": {"type": "api", "method": "POST", "service": "master-data", "levelsEndpoint": "get-all-g2p-geo-levels", "valuesEndpoint": "geo-level-values"}}], "panel-id": "village_location_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "polling_station", "widget-type": "input", "widget-label": "Polling Station", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.polling_station"}], "panel-id": "village_location_panel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "number", "widget-id": "gps_latitude", "widget-type": "input", "widget-label": "GPS Latitude", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.gps_latitude", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 6}}, {"widget": "number", "widget-id": "gps_longitude", "widget-type": "input", "widget-label": "GPS Longitude", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.gps_longitude", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 6}}], "panel-id": "village_location_panel_3", "panel-orientation": "vertical"}], "panel-id": "village_location_outer", "panel-orientation": "horizontal"}], "section-id": "village_location", "section-title": "Administrative Location", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'village_leadership_section',
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'FALSE',
    'village_leadership',
    'Village Leadership',
    'FALSE',
    0,
    'FALSE',
    30,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "text", "widget-id": "chairperson_name", "widget-type": "input", "widget-label": "Chairperson Name", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.chairperson_name"}, {"widget": "text", "widget-id": "chairperson_phone", "widget-type": "input", "widget-label": "Chairperson Phone", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.chairperson_phone"}], "panel-id": "village_leadership_panel_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "treasurer_name", "widget-type": "input", "widget-label": "Treasurer Name", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.treasurer_name"}, {"widget": "text", "widget-id": "treasurer_phone", "widget-type": "input", "widget-label": "Treasurer Phone", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.treasurer_phone"}], "panel-id": "village_leadership_panel_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "text", "widget-id": "secretary_name", "widget-type": "input", "widget-label": "Secretary Name", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.secretary_name"}, {"widget": "text", "widget-id": "secretary_phone", "widget-type": "input", "widget-label": "Secretary Phone", "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.secretary_phone"}], "panel-id": "village_leadership_panel_3", "panel-orientation": "vertical"}], "panel-id": "village_leadership_outer", "panel-orientation": "horizontal"}], "section-id": "village_leadership", "section-title": "Leadership", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_household_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_household',
    'Link individual to household',
    'FALSE',
    0,
    'FALSE',
    10,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "register-lookup", "widget-id": "household_lookup", "widget-type": "input", "widget-label": "Household", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.link_internal_record_id", "widget-data-source": {"type": "api", "method": "POST", "params": {"register_id": "9055ab43-c85d-4833-bd00-ca657bb72644"}, "service": "register", "endpoint": "records"}, "widget-lookup-config": {"page_size": 10, "action_label": "Click to Search Household", "search_placeholder": "Search by name or ID...", "select_record_label": "Select Household"}}], "panel-id": "household_lookup_inside_panel", "panel-orientation": "vertical"}], "panel-id": "household_lookup_outside_panel", "panel-orientation": "horizontal"}], "section-id": "individual_household", "section-title": "Household", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_member_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'household_members',
    'Individuals in this household',
    'FALSE',
    0,
    'TRUE',
    10,
    $json${"panels": [{"widgets": [{"widget": "dialog-table", "widget-id": "members_table", "widget-type": "table", "widget-label": "Household Members", "widget-readonly": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.records", "panel-column-span": 12, "panel-orientation": "vertical", "widget-data-add-label": "Add Member", "widget-data-operations": {"add": true, "edit": true, "remove": true}, "widget-data-columns": [{"widget": "text", "column-key": "first_name", "widget-type": "input", "widget-label": "First Name", "widget-required": true, "widget-data-path": "first_name"}, {"widget": "text", "column-key": "middle_name", "widget-type": "input", "widget-label": "Middle Name", "widget-required": true, "widget-data-path": "middle_name"}, {"widget": "text", "column-key": "last_name", "widget-type": "input", "widget-label": "Last Name", "widget-required": true, "widget-data-path": "last_name"}, {"widget": "text", "column-key": "additional_name", "widget-type": "input", "widget-label": "Additional Name", "widget-data-path": "additional_name"}, {"widget": "date", "column-key": "birth_date", "widget-type": "input", "widget-label": "Birthdate", "widget-data-path": "birth_date"}, {"widget": "select", "column-key": "gender", "widget-type": "input", "widget-label": "Gender", "widget-data-path": "gender", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "GENDER"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "text", "column-key": "phone", "widget-type": "input", "widget-label": "Phone", "widget-data-path": "phone"}]}], "panel-id": "panel_household_members"}], "section-id": "household_members", "section-title": "Household Members", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_village_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_village',
    'Link household to village',
    'FALSE',
    0,
    'FALSE',
    10,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "register-lookup", "widget-id": "village_lookup", "widget-type": "input", "widget-label": "Village", "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.link_internal_record_id", "widget-data-source": {"type": "api", "method": "POST", "params": {"register_id": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b"}, "service": "register", "endpoint": "records"}, "widget-lookup-config": {"page_size": 10, "action_label": "Click to Search Village", "search_placeholder": "Search by name or ID...", "select_record_label": "Select Village"}}], "panel-id": "village_lookup_inside_panel", "panel-orientation": "vertical"}], "panel-id": "village_lookup_outside_panel", "panel-orientation": "horizontal"}], "section-id": "household_village", "section-title": "Village", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'village_household_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'village_households',
    'Households in this village',
    'FALSE',
    0,
    'TRUE',
    10,
    $json${"panels": [{"widgets": [{"widget": "dialog-table", "widget-id": "households_table", "widget-type": "table", "widget-label": "Village Households", "widget-readonly": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.records", "panel-column-span": 12, "panel-orientation": "vertical", "widget-data-add-label": "Add Household", "widget-data-operations": {"add": true, "edit": true, "remove": true}, "widget-data-columns": [{"widget": "text", "column-key": "name", "column-group": "identity", "widget-type": "input", "widget-label": "Name", "widget-required": true, "widget-data-path": "name"}, {"widget": "number", "column-key": "household_size", "column-group": "identity", "widget-type": "input", "widget-label": "Household Size", "widget-data-path": "household_size", "widget-data-format": {"allowSigned": false, "numericType": "integer"}}, {"widget": "geo-hierarchy", "column-key": "geo_lowest_level_value_id", "column-group": "location", "widget-type": "input", "widget-label": "Location Hierarchy", "widget-data-path": {"value": "geo_lowest_level_value_id", "hierarchy": "geo_code_hierarchy_json"}, "widget-data-source": {"type": "api", "method": "POST", "service": "master-data", "levelsEndpoint": "get-all-g2p-geo-levels", "valuesEndpoint": "geo-level-values"}}, {"widget": "text", "column-key": "polling_station", "column-group": "location", "widget-type": "input", "widget-label": "Polling Station", "widget-data-path": "polling_station"}, {"widget": "number", "column-key": "gps_latitude", "column-group": "location", "widget-type": "input", "widget-label": "GPS Latitude", "widget-data-path": "gps_latitude", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 6}}, {"widget": "number", "column-key": "gps_longitude", "column-group": "location", "widget-type": "input", "widget-label": "GPS Longitude", "widget-data-path": "gps_longitude", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 6}}, {"widget": "text", "column-key": "bank_name", "column-group": "financial", "widget-type": "input", "widget-label": "Bank Name", "widget-data-path": "bank_name"}, {"widget": "text", "column-key": "branch_name", "column-group": "financial", "widget-type": "input", "widget-label": "Branch Name", "widget-data-path": "branch_name"}, {"widget": "text", "column-key": "branch_code", "column-group": "financial", "widget-type": "input", "widget-label": "Branch Code", "widget-data-path": "branch_code"}, {"widget": "text", "column-key": "account_number", "column-group": "financial", "widget-type": "input", "widget-label": "Account Number", "widget-data-path": "account_number"}, {"widget": "text", "column-key": "ifsc_code", "column-group": "financial", "widget-type": "input", "widget-label": "IFSC Code", "widget-data-path": "ifsc_code"}, {"widget": "select", "column-key": "financial_management", "column-group": "bank", "widget-type": "input", "widget-label": "Financial Management", "widget-data-path": "financial_management", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "FINANCIAL_MANAGEMENT"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "date", "column-key": "last_disbursement_date", "column-group": "bank", "widget-type": "input", "widget-label": "Last Disbursement Date", "widget-data-path": "last_disbursement_date"}, {"widget": "number", "column-key": "last_disbursement_amount", "column-group": "bank", "widget-type": "input", "widget-label": "Last Disbursement Amount", "widget-data-path": "last_disbursement_amount", "widget-data-format": {"allowSigned": false, "numericType": "decimal", "decimalPlaces": 2}}, {"widget": "select", "column-key": "training_needs", "column-group": "capacity", "widget-type": "input", "widget-label": "Training Needs", "widget-data-path": "training_needs", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "TRAINING_NEEDS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "select", "column-key": "loan_requirement", "column-group": "capacity", "widget-type": "input", "widget-label": "Loan Requirement", "widget-data-path": "loan_requirement", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "LOAN_REQUIREMENT"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "date", "column-key": "grand_required_in", "column-group": "capacity", "widget-type": "input", "widget-label": "Grant Required In", "widget-data-path": "grand_required_in"}, {"widget": "number", "column-key": "amount_required", "column-group": "capacity", "widget-type": "input", "widget-label": "Amount Required", "widget-data-path": "amount_required", "widget-data-format": {"allowSigned": false, "numericType": "integer"}}, {"widget": "select", "column-key": "amount_required_in", "column-group": "capacity", "widget-type": "input", "widget-label": "Amount Required In", "widget-data-path": "amount_required_in", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "AMOUNT_REQUIRED_IN"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}, {"widget": "boolean", "column-key": "signed_grant_agreement", "column-group": "capacity", "widget-type": "input", "widget-label": "Signed Grant Agreement", "widget-data-path": "signed_grant_agreement"}, {"widget": "select", "column-key": "grant_status", "column-group": "capacity", "widget-type": "input", "widget-label": "Grant Status", "widget-data-path": "grant_status", "widget-data-source": {"type": "api", "method": "POST", "params": {"attribute_id": "GRANT_STATUS"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_code"}}]}], "panel-id": "panel_village_households"}], "section-id": "village_households", "section-title": "Village Households", "section-editable": true}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'TRUE'
  ),
  (
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'individual_attachment_section',
    'a1a4d25a-1cd4-4356-abac-985a0b3c6bcd',
    'FALSE',
    'individual_attachment',
    'Attachments for Individual',
    'FALSE',
    0,
    'FALSE',
    40,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "file", "widget-id": "attachment_one", "widget-type": "input", "widget-label": "attachment_one", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.documents.attachment_one", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}, {"widget": "file", "widget-id": "attachment_two", "widget-type": "input", "widget-label": "attachment_two", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.documents.attachment_two", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}], "panel-id": "panel_individual_documents_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "file", "widget-id": "attachment_three", "widget-type": "input", "widget-label": "attachment_three", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.documents.attachment_three", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}, {"widget": "file", "widget-id": "attachment_four", "widget-type": "input", "widget-label": "attachment_four", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.documents.attachment_four", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}], "panel-id": "panel_individual_documents_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "file", "widget-id": "attachment_five", "widget-type": "input", "widget-label": "attachment_five", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.documents.attachment_five", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 2097152}}, {"widget": "file", "widget-id": "attachment_six", "widget-type": "input", "widget-label": "attachment_six", "widget-required": false, "widget-data-path": "a1a4d25a-1cd4-4356-abac-985a0b3c6bcd.documents.attachment_six", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 2097152}}], "panel-id": "panel_individual_documents_3", "panel-orientation": "vertical"}], "panel-id": "panel_individual_documents_main", "panel-orientation": "horizontal"}], "section-id": "individual_documents", "section-title": "individual_documents", "section-editable": true, "section-column-span": 3}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'FALSE'
  ),
  (
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'household_attachment_section',
    '9055ab43-c85d-4833-bd00-ca657bb72644',
    'FALSE',
    'household_attachment',
    'Attachments for Household',
    'FALSE',
    0,
    'FALSE',
    60,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "file", "widget-id": "attachment_one", "widget-type": "input", "widget-label": "attachment_one", "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.documents.attachment_one", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}, {"widget": "file", "widget-id": "attachment_two", "widget-type": "input", "widget-label": "attachment_two", "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.documents.attachment_two", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}], "panel-id": "panel_household_documents_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "file", "widget-id": "attachment_three", "widget-type": "input", "widget-label": "attachment_three", "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.documents.attachment_three", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}, {"widget": "file", "widget-id": "attachment_four", "widget-type": "input", "widget-label": "attachment_four", "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.documents.attachment_four", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}], "panel-id": "panel_household_documents_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "file", "widget-id": "attachment_five", "widget-type": "input", "widget-label": "attachment_five", "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.documents.attachment_five", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 2097152}}, {"widget": "file", "widget-id": "attachment_six", "widget-type": "input", "widget-label": "attachment_six", "widget-required": false, "widget-data-path": "9055ab43-c85d-4833-bd00-ca657bb72644.documents.attachment_six", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 2097152}}], "panel-id": "panel_household_documents_3", "panel-orientation": "vertical"}], "panel-id": "panel_household_documents_main", "panel-orientation": "horizontal"}], "section-id": "household_documents", "section-title": "household_documents", "section-editable": true, "section-column-span": 3}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'FALSE'
  ),
  (
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'village_attachment_section',
    'e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b',
    'FALSE',
    'village_attachment',
    'Attachments for Village',
    'FALSE',
    0,
    'FALSE',
    40,
    $json${"panels": [{"panels": [{"widgets": [{"widget": "file", "widget-id": "attachment_one", "widget-type": "input", "widget-label": "attachment_one", "widget-required": false, "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.documents.attachment_one", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}, {"widget": "file", "widget-id": "attachment_two", "widget-type": "input", "widget-label": "attachment_two", "widget-required": false, "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.documents.attachment_two", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}], "panel-id": "panel_village_documents_1", "panel-orientation": "vertical"}, {"widgets": [{"widget": "file", "widget-id": "attachment_three", "widget-type": "input", "widget-label": "attachment_three", "widget-required": false, "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.documents.attachment_three", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}, {"widget": "file", "widget-id": "attachment_four", "widget-type": "input", "widget-label": "attachment_four", "widget-required": false, "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.documents.attachment_four", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 5242880}}], "panel-id": "panel_village_documents_2", "panel-orientation": "vertical"}, {"widgets": [{"widget": "file", "widget-id": "attachment_five", "widget-type": "input", "widget-label": "attachment_five", "widget-required": false, "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.documents.attachment_five", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 2097152}}, {"widget": "file", "widget-id": "attachment_six", "widget-type": "input", "widget-label": "attachment_six", "widget-required": false, "widget-data-path": "e7c8f2a1-4b5d-4e6f-9a0b-1c2d3e4f5a6b.documents.attachment_six", "widget-data-options": {"accept": ".pdf,.jpg,.jpeg,.png", "maxSize": 2097152}}], "panel-id": "panel_village_documents_3", "panel-orientation": "vertical"}], "panel-id": "panel_village_documents_main", "panel-orientation": "horizontal"}], "section-id": "village_documents", "section-title": "village_documents", "section-editable": true, "section-column-span": 3}$json$,
    'FALSE',
    'FALSE',
    'FALSE',
    'FALSE'
  )
ON CONFLICT DO NOTHING;
