{{- if and .Values.connector.enabled .Values.connector.consumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-consumer
  labels: {{- include "connector.labels" . | nindent 4 }}
    app.kubernetes.io/component: connector-consumer
spec:
  replicas: {{ .Values.connector.consumer.replicaCount }}
  selector:
    matchLabels: {{- include "connector.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: connector-consumer
  template:
    metadata:
      labels: {{- include "connector.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: connector-consumer
    spec:
      serviceAccountName: {{ include "connector.serviceAccountName" . }}
      {{- include "connector.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.connector.postgresCheckerInit.enabled }}
      initContainers:
        {{- include "connector.postgresCheckerInit" . | nindent 8 }}
      {{- end }}
      containers:
        - name: connector-consumer
          image: "{{ .Values.connector.image.repository }}:{{ .Values.connector.image.tag }}"
          imagePullPolicy: {{ .Values.connector.image.pullPolicy }}
          args: ["consumer"]
          env:
            {{- include "connector.commonEnv" . | nindent 12 }}
          {{- if .Values.connector.consumer.resources }}
          resources: {{- toYaml .Values.connector.consumer.resources | nindent 12 }}
          {{- end }}
{{- end }}
